### ISSUE TITLE
Ability to define inbound udp port or socket object

### ISSUE THREAD

**Issue by nurdism** [gamedig/node-gamedig#149]
I'd like to use this lib for a discord bot, but running into a firewall issue, if you look [here](https://nodejs.org/api/dgram.html#dgram_socket_bind_options_callback) 

> For UDP sockets, causes the dgram.Socket to listen for datagram messages on a named port and optional address that are passed as properties of an options object passed as the first argument. If port is not specified or is 0, **_the operating system will attempt to bind to a random port._** If address is not specified, the operating system will attempt to listen on all addresses. Once binding is complete, a 'listening' event is emitted and the optional callback function is called.

this is causing timeouts on all requests due to the firewall. I'd like a way to either pass it an existing socket (preferable) or define the port to bind to.

**Comment by sonicsnes** [comment]
This is super low-priority if anything. Even the native clients for these games use randomized source ports, and they certainly don't allow the user to override them (usually). Is this behind a totally stateless firewall or something?

**Comment by nurdism** [comment]
its behind iptables using ufw with `default deny incoming` and `default allow outgoing`. With the firewall off, works as intended, with it on, it blocks the incoming packets from the request.

**Comment by sonicsnes** [comment]
Weird, I wouldn't expect any issue with the stock behavior with that sort of ufw setup. Afaik, ufw's just a facade over iptables, and iptables is certainly capable of statefully tracking the established udp connections out to servers, and should automatically allow the packages to come back from them.

That's the only configuration you have setup? Any chance we could get the output of `iptables -L` and `iptables -L -t nat`? (excluding anything private if you've got sensitive rules)

Not saying this is a good solution, but if this issue is blocking you, you could use an absolutely awful fragile monkey-patch like this (untested):
```
const dgram = require('dgram')
const gamedigSocket = require('gamedig/lib/GlobalUdpSocket');
const myUdpPort = 9999;
const oldCreateSocket = dgram.createSocket;
dgram.createSocket = () => {
    const socket = oldCreateSocket.apply(dgram, arguments);
    const oldBind = socket.oldBind;
    socket.bind = () => oldBind.call(socket, myUdpPort);
}
gamedigSocket._getSocket();
dgram.createSocket = oldCreateSocket;
```

**Comment by nurdism** [comment]
Wait, I just realized, I'm running in inside docker instance, (vscode remote dev container) with https://github.com/chaifeng/ufw-docker and some basic rules. I'm going to do a bit more digging over the weekend and see if I can pinpoint what exactly is blocking. I'm using dgram on another project and was running into the same issue, so i make it bind to a port and opened it on the docker container. 

ufw rules https://hastebin.com/iqubewuduh.txt
iptables -L https://hastebin.com/erusovediv.txt
iptables -L -t nat https://hastebin.com/owaqeyazuc.txt

I think its docker's internal routing thats causing the issue

**Comment by sonicsnes** [comment]
Oh yes! That makes a big difference. As far as I know, docker routing
doesn't consider ANY incoming udp packets to ever be related. I've had
similar issues with running unifi and plex in docker.

You're correct that specifying a port would be useful for this case.
Alternatively (although less secure), you can run the container with --net
host, which just gives it free reign on the host machine's network (in
which case itll just grab one of the host machine's udp ports and
everything would work fine).
