### ISSUE TITLE
Onset - Add Support

### ISSUE THREAD

**Issue by Murgator** [gamedig/node-gamedig#152]
A promising new game has been available since yesterday !

Onset: https://store.steampowered.com/app/1105810/Onset/

I would like to query this server but i try protocol-unreal2 and it does not work...

Thank you in advance for you help here is Onset servers:

35.246.156.170:7777 -> Battle Royale
51.91.165.24:7777 -> Cops and Robbers (EU-1)
66.70.207.242:7777 -> Cops and Robbers (US-1)

**Comment by Murgator** [comment]
Onset support tells me it uses this protocol: http://www.open-game-protocol.org/ on port 7776

**Comment by julien040** [comment]
**I don't know if any other games use this protocol, but Onset uses it.**
http://www.open-game-protocol.org/

**Comment by Murgator** [comment]
I have tested all gamedig protocols and none of them work. I also tried battlefield which apparently uses the OGP protocol but doesn't work either.

To use while waiting: https://github.com/mTxServ/php-open-game-protocol-client

**Comment by julien040** [comment]
Yeah, i saw this library. But I don't know how to use PHP.
So i'm waiting... : )

**Comment by sonicsnes** [comment]
Why would they choose a complex, abandoned query protocol from 2010 🤦‍♂

**Comment by julien040** [comment]
Do you think it's possible?
