### ISSUE TITLE
Add discord widget API

### ISSUE THREAD

**Issue by Douile** [gamedig/node-gamedig#156]
Would like to add a discord query to go along with teamspeak and mumble.

This is possible to do without a discord API key by using the widget API, however it requires servers to enable the widget option in settings.

Since I couldn't find documentation on this API here is a [link to a public example](https://discordapp.com/api/guilds/309408516857266178/widget.json)

It would involve a simple HTTP get request followed by JSON parsing.

API URL: `https://discordapp.com/api/guilds/{GUILDID}/widget.json`

Only issue is that servers cannot be addressed with IPs only discord snowflake IDs however I don't think this would be too much of a problem.

_I may make a pull request to add this_

**Comment by mmorrisontx** [comment]
Merged. Thank you!
