### ISSUE TITLE
Error: Failed all 1 attempts

### ISSUE THREAD

**Issue by hennyumut-zz** [gamedig/node-gamedig#161]
Hello, I use the 'gamedig' system but I get an error saying: "Error: Failed all 1 attempts" - (My 'gamedig' version: 2.0.20 / Server IP : 185.198.75.32:27015) Entire code;

`Gamedig.query({
      type: 'csgo',
      host: serverIP,
      socketTimeout: 3000
  }).then((state) => {
    let emb = new Discord.RichEmbed()
    .setTitle(state.name)
    .setColor("#E79E12")
    .setTimestamp()
    .setImage(`https://www.gametracker.com/server_info/${serverIP}:27015/b_560_95_1.png`)
    .addField("IP", serverIP, true)
    .addField("Players", state.raw.players.length + " / " + state.maxplayers, true)
    .addField("Map", state.map, true)
    .addField("Server Connect", `steam://connect/${sunucuIP}`, true)
    message.channel.send(emb).catch()
  }).catch((error) => {
    return message.channel.send(`${error}`)
  });`

**Comment by sonicsnes** [comment]
What's the console output if you add `debug: true`?

**Comment by hennyumut** [comment]
`Q#0 Query is running with options: { socketTimeout: 2000,
  attemptTimeout: 10000,
  maxAttempts: 1,
  port: 27015,
  protocol: 'valve',
  type: 'csgo',
  host: 'go32.oyunhost.net',
  debug: true }
Q#0 DNS Lookup: go32.oyunhost.net
Q#0 Standard Resolve: go32.oyunhost.net
Q#0 Found address: 185.198.75.32
Q#0 Requesting info ...
Q#0 185.198.75.32:27015 UDP-->
Q#0 Buffer length: 25 bytes
ff ff ff ff 54 53 6f 75 72 63 65 20 45 6e 67 69 6e 65 20 51 75 
            T  S  o  u  r  c  e     E  n  g  i  n  e     Q  u  
65 72 79 00 
e  r  y     

Q#0 UDP timeout detected
Q#0 Query failed with error Error: UDP - Timed out after 2000ms
    at Timeout.setTimeout (/rbd/pnpm-volume/fa872665-077a-4032-a9a5-b9f2ff0f467f/node_modules/gamedig/lib/Promises.js:7:25)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
^C`

**Comment by hennyumut** [comment]
?

**Comment by Almog1906** [comment]
I've got the same problem here.
Did you fix it?

**Comment by passivedragon** [comment]
Exact identical issue here with conanexiles.
I assume it hasn't been fixed.

**Comment by mmorrisontx** [comment]
All games have different protocol implementations. The valve protocol is pretty stable, which means if you get a timeout waiting for a UDP response when in debug mode, it's most likely that the server simply isn't configured to respond to query pings, or your ISP / firewall / router / server host is not allowing response UDP packet to make its way back to your gamedig instance. If you are having an issue with another variety of server, please open a new ticket with the IP and type of server in question, along with the output given when querying with `debug: true` / `--debug`.
