### ISSUE TITLE
Invalid game: assettocorsa

### ISSUE THREAD

**Issue by dgibbs64** [gamedig/node-gamedig#171]
Assetto Corsa is listed as a supported server however I get the following.

```
gamedig --type "assettocorsa" --host "127.0.0.1" --port 8081
{"error":"Invalid game: assettocorsa"}
```

**Comment by Rookie0ne** [comment]
Same problem here. Any solution to this?

**Comment by sonicsnes** [comment]
Looks like gamedig hasn't been published since the support was added. You can `npm install sonicsnes/node-gamedig` to install from the latest github commit if you don't want to wait.

**Comment by Rookie0ne** [comment]
Thank you @sonicsnes , that worked!

**Comment by dgibbs64** [comment]
Thanks for this. When is the next time it will be published?

**Comment by dgibbs64** [comment]
Looks like this has been updated as of version 2.0.21. I will close this
