### ISSUE TITLE
Soldat - Add Support

### ISSUE THREAD

**Issue by dgibbs64** [gamedig/node-gamedig#174]
I have been talking with a Soldat developer and I got this response after I asked about server queries.

> @DanGibbs "ASE" query was removed long time ago.. you can send a UDP packet with payload 6900 to ping the server, it should respond with 6A00 or you can download gamestat.txt using FileServer port (serverport + 10 TCP) https://wiki.soldat.pl/index.php/Gamestat.txt https://wiki.soldat.pl/index.php/Download_thread

So basically, ASE query does not work with soldat anymore and will need updating. I am going to look and see if I can get it working with my own query tool but getting it working with gamedig would be great :)

**Comment by sonicsnes** [comment]
Yay, yet another query protocol wooo. 😄
