### ISSUE TITLE
Space engineers torch servers.

### ISSUE THREAD

**Issue by Sanchezo** [gamedig/node-gamedig#183]
Hello! Great portion of Space Engineers servers use custom software called Torch. It uses port 27016 instead of 27015 like the regular ones. Could you add it to game list?

**Comment by mmorrisontx** [comment]
This should work properly if you specify the port in the query options. Is there a reason to add it as a separate game type?

**Comment by Sanchezo** [comment]
Ok, I didn't know about port option. Thanks.
