### ISSUE TITLE
requesting support for Astroneer 

### ISSUE THREAD

**Issue by StellarwhimsRepo** [gamedig/node-gamedig#188]
I tried protocol-valve to no avail. default port is 8777.

**Comment by mmorrisontx** [comment]
We can only query servers which respond to queries in some way. It doesn't seem that Astroneer has any documented query protocol (and you're right, I would expect it to be valve if there was one).

**Comment by StellarwhimsRepo** [comment]
I will try to reach out to them to see if there are plans, or if that tcp 1234 showing as listening has anything to do with it.

**Comment by mmorrisontx** [comment]
Closed since I don't think there is any query protocol for astroneer at this time. Please re-open if more information about a query protocol comes to light.
