### ISSUE TITLE
{"error":"Failed all 1 attempts"} - how to fix? (csgo)

### ISSUE THREAD

**Issue by botoboua** [gamedig/node-gamedig#194]
root@vps-1904:/home/node-gamedig-master# bin/gamedig.js --type csgo --host 195.18.248.68 --port 27016
{"error":"Failed all 1 attempts"}

root@vps-1904:/home/node-gamedig-master# bin/gamedig.js --type csgo --host 195.18.248.68 --port 27016 --debug
Q#0 Query is running with options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxAttempts: 1,
  port: 27016,
  protocol: 'valve',
  type: 'csgo',
  host: '195.18.248.68',
  debug: true
}
Q#0 DNS Lookup: 195.18.248.68
Q#0 Raw IP Address: 195.18.248.68
Q#0 Requesting info ...
Q#0 195.18.248.68:27016 UDP-->
Q#0 Buffer length: 25 bytes
ff ff ff ff 54 53 6f 75 72 63 65 20 45 6e 67 69 6e 65 20 51 75 
            T  S  o  u  r  c  e     E  n  g  i  n  e     Q  u  
65 72 79 00 
e  r  y     

Q#0 UDP timeout detected
Q#0 Query failed with error Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (/home/node-gamedig-master/lib/Promises.js:7:25)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
Error: Failed all 1 attempts
    at QueryRunner.run (/home/node-gamedig-master/lib/QueryRunner.js:88:21)
Attempt #1 - Port=27016 Retry=0:
Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (/home/node-gamedig-master/lib/Promises.js:7:25)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
root@vps-1904:/home/node-gamedig-master#

**Comment by cetteup** [comment]
Gamedig cannot connect to the server you are trying to query.

Are you sure both IP and query port are correct?

**Comment by mmorrisontx** [comment]
Closed due to inactivity. Please re-open if still an issue.
