### ISSUE TITLE
Failed all attempts on some servers

### ISSUE THREAD

**Issue by dftd** [gamedig/node-gamedig#198]
I was testing gamedig with a few random servers from Gametracker, some worked but most just returned "Failed all attempts" even though the servers are online.

What could be the cause of this? The only idea that comes to my mind is that they blocked all querying IP's but the Gametracker ones.

**Comment by xCausxn** [comment]
Hi @dftd ,

Do you have some examples, and also the command you are running to check this? 

Maybe they are running different query ports?

**Comment by dftd** [comment]
Here's a Call of Duty 1 example.
I also tried increasing the timeout. All servers work properly on Gametracker.

![image](https://user-images.githubusercontent.com/53878055/96276971-f651bc80-0fd3-11eb-9c2c-1053dd1dff39.png)

CoD 1 is on the Quake3 engine and as far as I know, it doesn't let you choose the query port.

**Comment by xCausxn** [comment]
Hi dftd,

I think there is some sort of datacenter filtering going on, maybe as a form of VPN detection.

Local Machine
![image](https://user-images.githubusercontent.com/1427375/96278846-e9ca6580-0fcd-11eb-8f9b-4d08c2d41223.png)

Server Side
![image](https://user-images.githubusercontent.com/1427375/96279110-2bf3a700-0fce-11eb-9018-4ce17efd1c26.png)

**Comment by dftd** [comment]
I actually just had a chat with the owner of one of these servers.
As I thought, he has a firewall that blocks such requests, while he whitelisted Gametracker IP's.

I guess there's no real solution to this...
