### ISSUE TITLE
Core - Strip colors universally across all engines, and add an option to disable

### ISSUE THREAD

**Issue by miguelsotobaez** [gamedig/node-gamedig#204]
Only appear colors code like ^1 ^2 in Bot but not in players.

I really like if we can see color codes in player name too.

` maxplayers: '32',`
 `  players: [ { frags: 0, ping: 23, name: "»A'den Skirata«" } ],`
 `  bots: [ { frags: 0, ping: 0, name: '^0SL^1.^0DrachaT' } ],`

**Comment by sonicsnes** [comment]
Seems unlikely if the protocol isn't returning it already. Strange that it's showing for bots only. If you run the query with `debug: true`, does the response data contain any of the color codes? If not, there's not much we can do about it.

**Comment by mmorrisontx** [comment]
Seems unlikely if the protocol isn't returning it already. Strange that it's showing for bots only. If you run the query with debug: true, does the response data contain any of the color codes? If not, there's not much we can do about it.

**Comment by miguelsotobaez** [comment]
@mmorrisontx I found the issue, the problme is in the file quake3.js in protocols folder.

`class Quake3 extends Quake2 {
    constructor() {
        super();
        this.sendHeader = 'getstatus';
        this.responseHeader = 'statusResponse';
    }
    async run(state) {
        await super.run(state);
        state.name = this.stripColors(state.name);
        for(const key of Object.keys(state.raw)) {
            state.raw[key] = this.stripColors(state.raw[key]);
        }
        for(const player of state.players) {
            player.name = this.stripColors(player.name);
        }
    }
    stripColors(str) {
        return str.replace(/\^(X.{6}|.)/g,'');
    }
}`

There are a string replace with some regexp to delete color format before the results.

I think i'm going to fork this repository and working for a fix. Maybe some parameter to alllow or disallow color formats.

Regards

**Comment by mmorrisontx** [comment]
Ah, I didn't realize this was one of the protocols where we strip color codes. Seems like a bug that we treat players and bots differently :)

**Comment by podrivo** [comment]
This seems something specific to Quake and has no other issues around this subject. Also, removing colors extra char from the object seems the correct approach. I guess this is safe to close.
