### ISSUE TITLE
TeamSpeak3 - Support non-standard query ports

### ISSUE THREAD

**Issue by xLeviNx** [gamedig/node-gamedig#205]
Anyone have success querying teamspeak3 with this?

I have attempted a few times using the api and querying, and it does fail. Multiple other users who also tested had the same issue

**Comment by Ramzi-Sah** [comment]
it works great fo me, just check the additional notes for ts3:

For teamspeak 3 queries to work correctly, the following permissions must be available for the guest server group:
Virtual Server
b_virtualserver_info_view
b_virtualserver_channel_list
b_virtualserver_client_list
Group
b_virtualserver_servergroup_list
b_virtualserver_channelgroup_list

**Comment by xLeviNx** [comment]
Currently tried using https://github.com/DiscordGSM/DiscordGSM to query via gamedig, but to no avail. Multiple users are having the same issue?

**Comment by mmorrisontx** [comment]
Do you have a server ip we can test with?

**Comment by Ramzi-Sah** [comment]
works as expected on my ts3, be sure to open your port for ServerQuery 10011/tcp

gamedig --type teamspeak3 gamestatus.xyz:9987

`
{"name":"Hookah-eSports - Ts³","map":"","password":false,"raw":{"virtualserver_unique_identifier":"GAZvZm73qX/PBLKo7Dbq0ryI                                                  z74=","virtualserver_name":"Hookah-eSports - Ts³","virtualserver_welcomemessage":"","virtualserver_platform":"Linux","virtu                                                  alserver_version":"3.12.1 [Build: 1585305527]","virtualserver_maxclients":"32","virtualserver_password":"","virtualserver_c                                                  lientsonline":"2","virtualserver_channelsonline":"27","virtualserver_created":"1592320751","virtualserver_uptime":"47422","                                                  virtualserver_codec_encryption_mode":"0","virtualserver_hostmessage":"","virtualserver_hostmessage_mode":"1","virtualserver                                                  _filebase":"files/virtualserver_1","virtualserver_default_server_group":"8","virtualserver_default_channel_group":"8","virt                                                  ualserver_flag_password":"0","virtualserver_default_channel_admin_group":"8","virtualserver_max_download_total_bandwidth":"                                                  18446744073709551615","virtualserver_max_upload_total_bandwidth":"18446744073709551615","virtualserver_hostbanner_url":"","                                                  virtualserver_hostbanner_gfx_url":"","virtualserver_hostbanner_gfx_interval":"0","virtualserver_complain_autoban_count":"99                                                  99999","virtualserver_complain_autoban_time":"0","virtualserver_complain_remove_time":"3600","virtualserver_min_clients_in_                                                  channel_before_forced_silence":"100","virtualserver_priority_speaker_dimm_modificator":"-18.0000","virtualserver_id":"1","v                                                  irtualserver_antiflood_points_tick_reduce":"5","virtualserver_antiflood_points_needed_command_block":"9999","virtualserver_                                                  antiflood_points_needed_ip_block":"99999","virtualserver_client_connections":"4","virtualserver_query_client_connections":"                                                  81","virtualserver_hostbutton_tooltip":"","virtualserver_hostbutton_url":"","virtualserver_hostbutton_gfx_url":"","virtuals                                                  erver_queryclientsonline":"1","virtualserver_download_quota":"18446744073709551615","virtualserver_upload_quota":"184467440                                                  73709551615","virtualserver_month_bytes_downloaded":"266769","virtualserver_month_bytes_uploaded":"9292062","virtualserver_                                                  total_bytes_downloaded":"818589","virtualserver_total_bytes_uploaded":"19595595","virtualserver_port":"9987","virtualserver                                                  _autostart":"1","virtualserver_machine_id":"","virtualserver_needed_identity_security_level":"8","virtualserver_log_client"                                                  :"0","virtualserver_log_query":"0","virtualserver_log_channel":"0","virtualserver_log_permissions":"1","virtualserver_log_s                                                  erver":"0","virtualserver_log_filetransfer":"0","virtualserver_min_client_version":"1560850141","virtualserver_name_phoneti                                                  c":"","virtualserver_icon_id":"0","virtualserver_reserved_slots":"0","virtualserver_total_packetloss_speech":"0.0000","virt                                                  ualserver_total_packetloss_keepalive":"0.0000","virtualserver_total_packetloss_control":"0.0000","virtualserver_total_packe                                                  tloss_total":"0.0000","virtualserver_total_ping":"89.0000","virtualserver_ip":"0.0.0.0, ::","virtualserver_weblist_enabled"                                                  :"1","virtualserver_ask_for_privilegekey":"0","virtualserver_hostbanner_mode":"1","virtualserver_channel_temp_delete_delay_                                                  default":"20","virtualserver_min_android_version":"1559834030","virtualserver_min_ios_version":"1559144369","virtualserver_                                                  nickname":"","virtualserver_antiflood_points_needed_plugin_block":"0","virtualserver_status":"online","connection_filetrans                                                  fer_bandwidth_sent":"0","connection_filetransfer_bandwidth_received":"0","connection_filetransfer_bytes_sent_total":"0","co                                                  nnection_filetransfer_bytes_received_total":"564859","connection_packets_sent_speech":"0","connection_bytes_sent_speech":"0                                                  ","connection_packets_received_speech":"0","connection_bytes_received_speech":"0","connection_packets_sent_keepalive":"9818                                                  ","connection_bytes_sent_keepalive":"402538","connection_packets_received_keepalive":"9817","connection_bytes_received_keep                                                  alive":"412331","connection_packets_sent_control":"950","connection_bytes_sent_control":"167751","connection_packets_receiv                                                  ed_control":"941","connection_bytes_received_control":"77022","connection_packets_sent_total":"10768","connection_bytes_sen                                                  t_total":"570289","connection_packets_received_total":"10758","connection_bytes_received_total":"489353","connection_bandwi                                                  dth_sent_last_second_total":"81","connection_bandwidth_sent_last_minute_total":"294","connection_bandwidth_received_last_se                                                  cond_total":"83","connection_bandwidth_received_last_minute_total":"91","channels":[{"cid":"11","pid":"0","channel_order":"                                                  0","channel_name":"[spacer]","channel_topic":"","total_clients":"0","channel_needed_subscribe_power":"0"},{"cid":"90","pid"                                                  :"0","channel_order":"11","channel_name":"[rspacer] https://discord.gg/VcmJugMc9J","channel_topic":"https://discord.gg/VcmJ                                                  ugMc9J","total_clients":"0","channel_needed_subscribe_power":"0"},{"cid":"91","pid":"0","channel_order":"90","channel_name"                                                  :"[rspacer2] Ts³ : Various-eSports","channel_topic":"","total_clients":"0","channel_needed_subscribe_power":"0"},{"cid":"36                                                  ","pid":"0","channel_order":"91","channel_name":"[*spacer2]━","channel_topic":"","total_clients":"-1","channel_needed_subsc                                                  ribe_power":"75"},{"cid":"12","pid":"0","channel_order":"36","channel_name":"[cspacer] Eingangshalle","channel_topic":"","t                                                  otal_clients":"2","channel_needed_subscribe_power":"0"},{"cid":"35","pid":"0","channel_order":"12","channel_name":"[*spacer                                                  1]━","channel_topic":"","total_clients":"-1","channel_needed_subscribe_power":"75"},{"cid":"39","pid":"0","channel_order":"                                                  35","channel_name":"[cspacer1]Hookah eSports\\pAdministration","channel_topic":"","total_clients":"0","channel_needed_subsc                                                  ribe_power":"0"},{"cid":"41","pid":"0","channel_order":"39","channel_name":"Projektleitung","channel_topic":"","total_clien                                                  ts":"-1","channel_needed_subscribe_power":"65"},{"cid":"43","pid":"0","channel_order":"41","channel_name":"Support Team","c                                                  hannel_topic":"","total_clients":"0","channel_needed_subscribe_power":"0"},{"cid":"85","pid":"0","channel_order":"43","chan                                                  nel_name":"Ticket Team","channel_topic":"","total_clients":"0","channel_needed_subscribe_power":"0"},{"cid":"45","pid":"0",                                                  "channel_order":"85","channel_name":"Team Talk 1","channel_topic":"","total_clients":"0","channel_needed_subscribe_power":"                                                  0"},{"cid":"51","pid":"0","channel_order":"45","channel_name":"Team Talk 2","channel_topic":"","total_clients":"0","channel                                                  _needed_subscribe_power":"0"},{"cid":"47","pid":"0","channel_order":"51","channel_name":"[cspacer2]Hookah eSports \\p Suppo                                                  rt","channel_topic":"","total_clients":"0","channel_needed_subscribe_power":"0"},{"cid":"87","pid":"0","channel_order":"47"                                                  ,"channel_name":"┌ Support 1","channel_topic":"","total_clients":"0","channel_needed_subscribe_power":"0"},{"cid":"88","pid                                                  ":"0","channel_order":"87","channel_name":"├ Support 2","channel_topic":"","total_clients":"0","channel_needed_subscribe_po                                                  wer":"0"},{"cid":"89","pid":"0","channel_order":"88","channel_name":"└ Support 3","channel_topic":"","total_clients":"0","c                                                  hannel_needed_subscribe_power":"0"},{"cid":"92","pid":"0","channel_order":"89","channel_name":"→ Support Wartehalle","chann                                                  el_topic":"","total_clients":"0","channel_needed_subscribe_power":"0"},{"cid":"58","pid":"0","channel_order":"92","channel_                                                  name":"[*spacer3]━","channel_topic":"","total_clients":"-1","channel_needed_subscribe_power":"70"},{"cid":"60","pid":"0","c                                                  hannel_order":"58","channel_name":"[cspacer]━━━━━━━❪ Öffentlich ❫━━━━━━━","channel_topic":"","total_clients":"-1","channel_                                                  needed_subscribe_power":"70"},{"cid":"61","pid":"0","channel_order":"60","channel_name":"┌ Fortnite \\p Creativ","channel_t                                                  opic":"","total_clients":"0","channel_needed_subscribe_power":"0"},{"cid":"62","pid":"0","channel_order":"61","channel_name                                                  ":"├ Fortnite \\p Duo´s","channel_topic":"","total_clients":"0","channel_needed_subscribe_power":"0"},{"cid":"63","pid":"0"                                                  ,"channel_order":"62","channel_name":"├ Fortnite \\p Trio´s","channel_topic":"","total_clients":"0","channel_needed_subscri                                                  be_power":"0"},{"cid":"64","pid":"0","channel_order":"63","channel_name":"├ Fortnite \\p Team","channel_topic":"","total_cl                                                  ients":"0","channel_needed_subscribe_power":"0"},{"cid":"65","pid":"0","channel_order":"64","channel_name":"└ Fortnite \\p                                                   General","channel_topic":"","total_clients":"0","channel_needed_subscribe_power":"0"},{"cid":"66","pid":"0","channel_order"                                                  :"65","channel_name":"[*spacer5]━","channel_topic":"","total_clients":"-1","channel_needed_subscribe_power":"75"},{"cid":"6                                                  8","pid":"0","channel_order":"66","channel_name":"[cspacer7] ❪ Userbereich ❫","channel_topic":"","total_clients":"0","chann                                                  el_needed_subscribe_power":"0"},{"cid":"69","pid":"0","channel_order":"68","channel_name":"[cspacer9]","channel_topic":"","                                                  total_clients":"0","channel_needed_subscribe_power":"0"}]},"maxplayers":"32","players":[{"clid":"84","cid":"12","client_dat                                                  abase_id":"38","client_type":"0","name":"Ramzi Sah"}],"bots":[],"connect":"gamestatus.xyz:9987","ping":2}
`

**Comment by xLeviNx** [comment]
> Do you have a server ip we can test with?


104.192.225.22:9987 . I ultimately have another bot now querying it, just not sure why it is not compatible with ts3 and the other application I sent a link above for. Will continue to dig more for answers.

**Comment by mmorrisontx** [comment]
Your server doesn't seem to be responding on tcp port 10011 at all. All teamspeak querying occurs through tcp port 10011 (regardless of the voice port for the server).

```
$ bin/gamedig.js --type teamspeak3 104.192.225.22:9987 --debug --givenPortOnly
Q#0 Query is running with options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxAttempts: 1,
  port: 9987,
  protocol: 'teamspeak3',
  type: 'teamspeak3',
  host: '104.192.225.22',
  debug: true,
  givenPortOnly: true
}
Q#0 DNS Lookup: 104.192.225.22
Q#0 Raw IP Address: 104.192.225.22
Q#0 104.192.225.22:10011 TCP Connecting
Q#0 Query failed with error Error: TCP Opening - Timed out after 2000ms
```

**Comment by xLeviNx** [comment]
We have it querying it at 10010. Can you try with that tcp port?

**Comment by mmorrisontx** [comment]
I think the query port is actually hard-coded in gamedig at the moment. You could change it manually in teamspeak3.js as a temporary solution. I wasn't even aware the query port could be changed, since most server providers host a giant multi-server, with tons of different voice ports but leave the query port as the default of 10011.

**Comment by xLeviNx** [comment]
Just falling back on this. Any hopes of making sure the TS query isn't hardcoded?

**Comment by mmorrisontx** [comment]
Huh, apparently we had support for this all along and it just never got documented. You can specify teamspeakQueryPort in the gamedig query options, and it'll use that port rather than 10011.
