### ISSUE TITLE
Savage 2

### ISSUE THREAD

**Issue by Badyyy** [gamedig/node-gamedig#206]
Hi there. I'm the last one to run savage2 servers trying to keep it alive. It would be a dream to show the server status in my discord. To motivate people to connect
![Screenshot_8](https://user-images.githubusercontent.com/69426079/104063928-5637b800-51fd-11eb-8455-5f5e7f5745ca.png)

**Comment by mmorrisontx** [comment]
Added in gamedig 2.0.24.

**Comment by Ramzi-Sah** [comment]
works great thank you @mmorrisontx.
