### ISSUE TITLE
CS:GO Dosen't return players name

### ISSUE THREAD

**Issue by Elior2739** [gamedig/node-gamedig#207]
Hi

I'm trying to query a cs go server but when I try to get players name I'm getting this:
```
[ {}, {}, {} ]
```

Is GameDig can't get players name?

**Comment by mmorrisontx** [comment]
Double-check the gamedig notes for CS:GO:

https://github.com/gamedig/node-gamedig#csgo
> To receive a full player list response from CS:GO servers, the server must have set the cvar: host_players_show 2
