### ISSUE TITLE
Importing Gamedig throwing split error

### ISSUE THREAD

**Issue by web-developer032** [gamedig/node-gamedig#208]
Installed this package in my react-app and just copy your code and pasted in my app. then changed type and host and then running throwed an error. So i just commented that code and just ran that import thats also thorwing the same error.
TypeError: Cannot read property 'split' of undefined

I am attaching screenshot.
![image](https://user-images.githubusercontent.com/40429729/105716885-4203f280-5f41-11eb-8163-ab3ccb4f1315.png)

this is my code.
![image](https://user-images.githubusercontent.com/40429729/105717073-7e375300-5f41-11eb-9aac-f1e18445f6a5.png)

**Comment by mmorrisontx** [comment]
Gamedig cannot run inside the browser. Game query protocols depend on raw udp and tcp sockets, which browsers do not allow. Gamedig can only run under nodejs, server-side.

**Comment by web-developer032** [comment]
what if i dont have anyserver but want to use it? how can i achieve that?

**Comment by mmorrisontx** [comment]
This isn't possible. The browser is not able to query game servers directly using the network protocols they require.

**Comment by web-developer032** [comment]
Ok Thank you <3
