### ISSUE TITLE
Get the wipe date from a Rust server

### ISSUE THREAD

**Issue by Murgator** [gamedig/node-gamedig#209]
Hello, I would like to know if it is possible to get the wipe date of a Rust server ?

And if yes, how ? I get "uptime" but I don't see "wipe date".

Test servers:
89.34.96.40:28015
79.99.161.218:28015

Thank you in advance,
David.

**Comment by mmorrisontx** [comment]
Doesn't look like it. The `raw` field containes all of the raw data the server provides in addition to the standard player list and such, but it doesn't seem to contain what you're looking for:

```
  "raw": {
    "protocol": 17,
    "folder": "rust",
    "game": "Rust",
    "steamappid": 0,
    "numplayers": 1,
    "numbots": 0,
    "listentype": "d",
    "environment": "w",
    "secure": 1,
    "version": "2279",
    "steamid": "90142897987634184",
    "tags": "mp50,cp1,ptrak,qp0,v2279,h5c706e58,stok,born1612468053,gmrust,oxide
,modded",
    "gameid": "252490",
    "rules": {
      "build": "58558",
      "description_0": "Vastitude|PVE|5x|No Decay|No Raiding|No Killing|Special
Events",
      "description_01": "",
      "description_02": "",
      "description_03": "",
      "description_04": "",
      "description_05": "",
      "description_06": "",
      "description_07": "",
      "description_08": "",
      "description_09": "",
      "description_10": "",
      "description_11": "",
      "description_12": "",
      "description_13": "",
      "description_14": "",
      "description_15": "",
      "ent_cnt": "144624",
      "fps": "223",
      "fps_avg": "223.73",
      "gc_cl": "369",
      "gc_mb": "1716",
      "gmd": "The default Rust survival gamemode",
      "gmn": "rust",
      "gmt": "Rust: Survival Mode",
      "gmu": "https://rust.facepunch.com",
      "hash": "5c706e58",
      "headerimage": "https://imgur.com/a/vqbaEdC",
      "logoimage": "",
      "pve": "False",
      "uptime": "18797",
      "url": "https://steamcommunity.com/groups/vastitudee",
      "world.seed": "1442549665",
      "world.size": "4000"
    }
  },
```

unless `world.seed` is a timestamp, but that seems unlikely since `1442549665` would be a time from back in 2015...

**Comment by Murgator** [comment]
strange that we cannot retrieve this date because it is in the list of servers in the game. Anyway, thank you for your answer!

**Comment by mmorrisontx** [comment]
I'm surprised it's in the server list. Any way you could trace the query with wireshark? I guess it's possible the in-game browser uses some custom rust protocol rather than the steam query that we use.

**Comment by mmorrisontx** [comment]
I attached wireshark to my own copy of rust, and found it queries exactly the same that gamedig does. However, then I peeked around in the retrieved data a bit... and *facepalm*

In the raw.tags string, there's a field called `born`. In the example I posted above, the tag is `born1612468053`. This is a unix timestamp representing the wipe date.

I think parsing this within gamedig is probably a bit out of scope, but you should be able to iterate over the raw.tags.split(',') and parse the born tag as a timestamp yourself 😄
