### ISSUE TITLE
Support challenges in A2S_INFO (Valve)

### ISSUE THREAD

**Issue by Sinaloense** [gamedig/node-gamedig#210]
Valve did changes to the A2S_INFO protocol, which will help mitigate flood / DoS.

Right now it can only be optionally activated through environment variables, more information at:
[https://steamcommunity.com/discussions/forum/14/2974028351344359625/](https://steamcommunity.com/discussions/forum/14/2974028351344359625/)
[https://steamcommunity.com/discussions/forum/14/2989789048633291344/](https://steamcommunity.com/discussions/forum/14/2989789048633291344/)

Could you add support to gamedig?
I tried to do it myself, but I can't understand how to do it.

Apparently in another library from PHP they did adding this code: https://github.com/xPaw/PHP-Source-Query/commit/7c8e5add773cd038384da96dc82f60038366bc1b

**Comment by mmorrisontx** [comment]
I believe our implementation of the protocol should already handle this. We watch for challenge responses coming back from any request packets, and if we get one, we always re-send the current request with the new challenge.

**Comment by Sinaloense** [comment]
Dosn´t work for me when set the environment variable:
`STEAM_GAMESERVER_A2S_INFO_REQUIRE_CHALLENGE = 1`

Could you try with this IP of left4dead2?
`104.243.46.242:27030`

**Comment by mmorrisontx** [comment]
Should be fixed in 2.0.25

**Comment by Sinaloense** [comment]
Thanks, now is working 💯
