### ISSUE TITLE
Team is `NaN` for Codename Eagle players

### ISSUE THREAD

**Issue by rexxars** [gamedig/node-gamedig#213]
Codename Eagle sends the following players response:

```js
{
  player_0: 'rexxars',
  frags_0: '0',
  deaths_0: '7',
  skill_0: '0',
  ping_0: '0',
  team_0: 'red'
}
```

It appears that the `Gamespy1` logic expects the team to be an integer and tries to parse it using `parseInt()`, which results in `NaN`. Dropping the `parseInt` call results in the expected "red" value, but I'm not sure if this breaks other games, given that there are no tests...

Thoughts?

**Comment by mmorrisontx** [comment]
`name` is the only field of the player object that we really make any guarantees about, and even it can be missing entirely. I almost regret not throwing all non-name fields into an unstable `raw` subobject like we do with the unstable raw server state.

Not sure of the best way forward for this, but NaN itself probably already breaks client apps in unexpected and wonderful ways.

**Comment by rexxars** [comment]
I suppose one could check if the value is numeric ("will parse to a valid integer") and only parse it if that is the case, maybe? I hope no one is _relying_ on it being NaN? ;)

**Comment by mmorrisontx** [comment]
There's a pending change waiting for a major version bump (disable the slow details subquery for source protocol by default), so maybe we can clean this up at the same time and just bump the major to 3.0. We can put everything except `name` in a raw subobject at the same time, and then changes like this can be done whenever.
