### ISSUE TITLE
Gamedig doesn't work for MTA:SA anymore

### ISSUE THREAD

**Issue by DevPrio** [gamedig/node-gamedig#216]
The server that I'm trying to query: https://www.game-state.com/164.132.205.171:22003/
I also tried it on other servers but it doesn't seem to work
Here's the debug output
`Q#0 Starting
Q#0 Protocol: Ase
Q#0 Options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxAttempts: 1,
  port: 22003,
  protocol: 'ase',
  type: 'mtasa',
  host: '164.132.205.171',
  debug: true,
  givenPortOnly: true
}
Q#0 DNS Lookup: 164.132.205.171
Q#0 Raw IP Address: 164.132.205.171
Q#0 164.132.205.171:22003 UDP-->
Q#0 Buffer length: 1 bytes
73 
s  

Q#0 UDP timeout detected
Q#0 Query failed with error Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (/home/runner/Prio/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Server is offline`

**Comment by mmorrisontx** [comment]
MTASA operates its query protocol on a separate port, which is typically 22126. Gamedig attempts to find this port automatically (by adding 123 to the port you specify, the default being 22003), but if this isn't the case for your server, it'll time out. There's no way for us to detect the proper query port automatically if it's not 123 higher than the given game port, you'll have to discover that yourself in some other way.

**Comment by mmorrisontx** [comment]
Please re-open this issue if this continues to be a problem.
