### ISSUE TITLE
Pls. i too silly to understand this

### ISSUE THREAD

**Issue by lilarin** [gamedig/node-gamedig#218]
Can sombody explain me how to install this and make work pls? I don't know javascript, please don't be angry (
I installed everything successfully, but I can't figure out what to do with the code in the description
const Gamedig = require ('gamedig');
Gamedig.query ({
     type: 'minecraft',
     host: 'mc.example.com'
}). then ((state) => {
     console.log (state);
}). catch ((error) => {
     console.log ("Server is offline");
});
and can't figure out what to do with the token. I managed to modify the code so as to import the token from the .json file, but the part with
     type: 'minecraft',
     host: 'mc.example.com'
I do not understand..

**Comment by EInterStellar** [comment]
`Gamedig.query` takes a javascript object as a parameter. the object must contain 2 properties: `type` and `host`.
`type` is the game id that you want to query and get the data from. (you can find every game's id in the README section)
`host` is ip or domain of the server that you want to query.

If you are confused about `.then` and `.catch` you must learn javascript Promises.
And this:
```
(state) => {
    console.log (state);
}
```
Is a function that takes state as a parameter and logs it. these types of function are called Arrow functions.

**Comment by lilarin** [comment]
i don`t understand how to launch this.. what should i do with that
```
const Gamedig = require ('gamedig');
Gamedig.query ({
type: 'minecraft',
host: 'mc.example.com'
}). then ((state) => {
console.log (state);
}). catch ((error) => {
console.log ("Server is offline");
});
```

**Comment by lilarin** [comment]
It may sound arrogant, but if someone gives me a copy of their working bot without their token so that I can understand what is wrong with me and what I am doing wrong, I would be very grateful..

**Comment by xcpep** [comment]
I haven't got a working example of GameDig but the examples should show you everything you need.

Upload your code to a repository or to here and we can try to help more :)

**Comment by lilarin** [comment]
Ok .. Just to start .. I don't know js at all. I downloaded the zip file, installed gamedig, but then I don’t understand what to do, and this is my problem ..
I run the bot and I get in the terminal this

```
PS C: \ Users \ User \ Desktop \ node-gamedig-master> node index.js
internal / modules / cjs / loader.js: 883
   throw err;
   ^

Error: Cannot find module 'C: \ Users \ User \ Desktop \ node-gamedig-master \ index.js'
     at Function.Module._resolveFilename (internal / modules / cjs / loader.js: 880: 15)
     at Function.Module._load (internal / modules / cjs / loader.js: 725: 27)
     at Function.executeUserEntryPoint [as runMain] (internal / modules / run_main.js: 72: 12)
     at internal / main / run_main_module.js: 17: 47 {
   code: 'MODULE_NOT_FOUND',
   requireStack: []
}
PS C: \ Users \ User \ Desktop \ node-gamedig-master>
```

**Comment by xcpep** [comment]
Can you give us some context on what you're trying to achieve?

You should be able to achieve a basic setup by doing the following:

1.  Create a new folder called `project`
2. Create a file inside the folder called `index.js`  with the following code, but change the host to a server that actually exists:
```const Gamedig = require ('gamedig');
Gamedig.query ({
type: 'minecraft',
host: 'mc.example.com'
}). then ((state) => {
console.log (state);
}). catch ((error) => {
console.log ("Server is offline");
});
```
3. Open a command prompt window in that folder, and type `npm install gamedig`
4. Run the command `node index.js` and it should print the results from the server.

**Comment by lilarin** [comment]
i did it but i got an error.
https://i.imgur.com/z47ASWo.png

**Comment by xcpep** [comment]
Scratch that and try to follow the guide I posted above :)

**Comment by lilarin** [comment]
I did everything as you said, but nothing has changed for me. And I also can't install gamedig again..
```
PS C:\Users\User\Desktop\node-gamedig-master\project> npm install gamedig
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "gamedig" under a package
npm ERR! also called "gamedig". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2021-03-15T16_25_07_390Z-debug.log
```

**Comment by lilarin** [comment]
When run in terminal it outputs this
```
PS C:\Users\User\Desktop\node-gamedig-master\discord-bot> node index.js
C:\Users\User\Desktop\node-gamedig-master\discord-bot\index.js:3
Gamedig.query ({
^

ReferenceError: Gamedig is not defined
    at Object.<anonymous> (C:\Users\User\Desktop\node-gamedig-master\discord-bot\index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by SkullMasher** [comment]
You forgot the first line in index.js
`const Gamedig = require('gamedig');`

**Comment by EInterStellar** [comment]
@lilarin Did you cloned the repository? The folder named `node-gamedig-master` sounds like you cloned this repository.
You don't need to clone or download this repository at all.
just install it using npm and you can `require` it in any js file that is inside the directory you installed gamedig or subdirectories

**Comment by lilarin** [comment]
I stil can not launch this code..

**Comment by lilarin** [comment]
https://github.com/lilarin/bot_not_working
help pls..
what should i do? I can not understand

**Comment by mmorrisontx** [comment]
This issue board is specifically for technical issues related to the internals of gamedig itself. For general javascript and npm help, you may have better luck asking in a general forum such as stackoverflow or reddit.
