### ISSUE TITLE
Gamedig requires node 12, but indicates node 10 compatibility

### ISSUE THREAD

**Issue by freezy099** [gamedig/node-gamedig#220]
Used gamedig to create a status checker of a bot as intended, installed gamedig on both my computer and the server i was attempting to host my bot off of. When run off my laptop the bot worked fine and there were no issues however when used in command line on my server was recieving the following error: [Error] (https://cdn.discordapp.com/attachments/574044623912304652/827614055493402654/unknown.png) I then checked all my instals that would affect Gamedig such as Node and updated Gamedig just incase there was an issue with installation but i am stilling recieving the same error.

**Comment by freezy099** [comment]
Now not working whatsoever despite doing so earlier without any code changing.

**Comment by xCausxn** [comment]
Just to give more context can you run node -v on both the server and your local machine and post that information as well :)

**Comment by freezy099** [comment]
https://github.com/freezy099/arcbot2 - My Index
Personal Computer Version of Node.js: v15.12.0
Server: v10.24.0 (Updated it several times no idea why it hasnt gone up)

**Comment by xCausxn** [comment]
I recommend using these when installing node, unless you want to use a node version manager.

https://github.com/nodesource/distributions#installation-instructions

**Comment by mmorrisontx** [comment]
I believe we accidentally dropped node 10 support in v3.0.0. Node 12 is now required, but I'm not sure it's worth fixing since the node 10 maintenance period ends in just a couple months.
