### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tomaslxc** [gamedig/node-gamedig#221]
> Error: Failed all 2 attempts
    at QueryRunner.run (/home/runner/Texasroleplay/node_modules/gamedig/lib/QueryRunner.js:88:21)
Attempt #1 - Port=22136 Retry=0:
Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (/home/runner/Texasroleplay/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Attempt #2 - Port=22013 Retry=0:
Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (/home/runner/Texasroleplay/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
<

Node: 12
Gamedig: latest

I tried with other servers but it gives me the same error

**Comment by mmorrisontx** [comment]
What server and type?

**Comment by tomaslxc** [comment]
I just saw that gamedig is not working on replit.com. Also thanks for the help

**Comment by mmorrisontx** [comment]
Ah yeah, any shared hosted environment is probably containerized, which means you won't get replies back from udp requests.

**Comment by henrikwirth** [comment]
@tomaslxc I found a workaround if you are interested. I'm using Netlify Functions (Free) to have a serverless function running the gamedig query for me.

**Netlify Function:**

```
const Gamedig = require('gamedig');

exports.handler = async function(event, context) {

  let result =  await Gamedig.query({
    type: 'valheim',
    host: process.env.SERVER_IP,
    port: process.env.SERVER_PORT
  })

  delete result['connect'];
  
  return {
    statusCode: 200,
    body: JSON.stringify(result)
  };
}
```

**Replit:**

```
const fetchServerInfo = async () => {
  const response = await fetch(process.env.NETLIFY_FUNCTION);
  const data = await response.json();

  console.log(data);
  return data;
}

const serverInfo = fetchServerInfo();
```

You probably also want to add error handling and such.

**Comment by mmorrisontx** [comment]
Please open a new ticket if this isn't resolved by using a different host provider supporting udp callbacks.
