### ISSUE TITLE
GameSpy2 does not adhere to new player structure for 3.x (name, raw)

### ISSUE THREAD

**Issue by cetteup** [gamedig/node-gamedig#222]
Hello again!

I just upgraded to 3.0.0 and noticed that my GameSpy parsing setup did not work for Battlefield Vietnam (GameSpy2), while working just fine for GameSpy1 and 3 with the new player structure of `name` plus `raw`.

Dug through the code for the GameSpy2 protocol and I believe to have found the reason: Instead of pushing to the player array in the state/results (which adds the player in the 3.x format), `state.players` is directly set to the player list returned by the server (line 28 and below):

```javascript
// Parse players
{
    const body = await this.sendPacket([0, 0xff, 0]);
    const reader = this.reader(body);
    state.players = this.readFieldData(reader);
}
```

At least for Battlefield Vietnam, adding players like so instead works fine:
```javascript
// Parse players
{
    const body = await this.sendPacket([0, 0xff, 0]);
    const reader = this.reader(body);
    const players = this.readFieldData(reader);
    for (const player of players) {
        state.players.push(players);
    }
}
```

I can send a pull request for this, but it might need some more testing with other GameSpy2 games.

Cheers,
cetteup

**Comment by mmorrisontx** [comment]
Looks like assettocorsa, fivem, and gamespy1 may have similar issues.
