### ISSUE TITLE
Error: Failed all 1 attempts

### ISSUE THREAD

**Issue by blackopss** [gamedig/node-gamedig#224]
logs :
Q#0 Starting
Q#0 Protocol: FiveM
Q#0 Options: {
  socketTimeout: 2000,
  attemptTimeout: '20000',
  maxAttempts: 1,
  port: 30120,
  protocol: 'fivem',
  type: 'fivem',
  host: '194.45.197.16',
  debug: true
}
Q#0 DNS Lookup: 194.45.197.16
Q#0 Raw IP Address: 194.45.197.16
Q#0 194.45.197.16:30120 UDP-->
Q#0 Buffer length: 16 bytes
ff ff ff ff 67 65 74 69 6e 66 6f 20 78 78 78 00 
            g  e  t  i  n  f  o     x  x  x     

Q#0 UDP timeout detected
Q#0 Query failed with error Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (/home/runner/MonstrousHorizontalConversion/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Error: Failed all 1 attempts

**Comment by mmorrisontx** [comment]
This simply means that your server isn't up and responding to queries. You can verify if gamedig is working by querying one of the public fivem servers from https://www.gs4u.net/en/fivem/ .

**Comment by blackopss** [comment]
> This simply means that your server isn't up and responding to queries. You can verify if gamedig is working by querying one of the public fivem servers from https://www.gs4u.net/en/fivem/ .

i try a lot of servers and not work

**Comment by cetteup** [comment]
Where are you running the queries from? Your local PC?

**Comment by blackopss** [comment]
> Where are you running the queries from? Your local PC?

i have host for bot

**Comment by xCausxn** [comment]
I cant seem to find the server listed on https://servers.fivem.net/ when using the IP specified in the OP?

Is the server still online / people able to join it?

**Comment by blackopss** [comment]
> I cant seem to find the server listed on https://servers.fivem.net/ when using the IP specified in the OP?
> 
> Is the server still online / people able to join it?

https://servers.fivem.net/servers/detail/oapm3r

**Comment by blackopss** [comment]
> I cant seem to find the server listed on https://servers.fivem.net/ when using the IP specified in the OP?
> 
> Is the server still online / people able to join it?

see this
http://194.45.197.16:30120/players.json
http://194.45.197.16:30120/info.json

**Comment by mmorrisontx** [comment]
> http://194.45.197.16:30120/players.json

It seems this server isn't responding to UDP packets. There is both a udp and http tcp request involved in the fivem query protocol. Is it possible there is a firewall on this machine blocking udp on that port?

**Comment by blackopss** [comment]
> > http://194.45.197.16:30120/players.json
> 
> It seems this server isn't responding to UDP packets. There is both a udp and http tcp request involved in the fivem query protocol. Is it possible there is a firewall on this machine blocking udp on that port?

port 30120?

**Comment by f1ames0ff** [comment]
@mmorrisontx I have similar issue.

This code gives error `Error: Failed all 2 attempts...`
```ts
gamedig.query({
            'valheim',
            '<my_ip>:2456'
        }).then(stats => {
          console.log(stats);
        }).catch(error => {
          console.error(error);
        });
```

But cmd command gives normal stats:
`gamedig --type valheim <my_ip>:2456`

Why is so?

*Full stack trace*

```
Error: Failed all 2 attempts
    at QueryRunner.run (D:\Documents\Projects\f1am3d-games-web-page\node_modules\gamedig\lib\QueryRunner.js:88:21)
    at Gamedig.query (D:\Documents\Projects\f1am3d-games-web-page\node_modules\gamedig\lib\index.js:11:16)
    at Function.query (D:\Documents\Projects\f1am3d-games-web-page\node_modules\gamedig\lib\index.js:19:16)
    at StatsController.getValheimStats (D:\Documents\Projects\f1am3d-games-web-page\packages\backend\src\controllers\stats.controller.ts:11:16)
    at D:\Documents\Projects\f1am3d-games-web-page\packages\backend\node_modules\@nestjs\core\router\router-execution-context.js:46:28
    at D:\Documents\Projects\f1am3d-games-web-page\packages\backend\node_modules\@nestjs\core\router\router-proxy.js:9:17
Attempt #1 - Port=2457 Retry=0:
Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (D:\Documents\Projects\f1am3d-games-web-page\node_modules\gamedig\lib\Promises.js:7:25)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
Attempt #2 - Port=2457 Retry=1:
Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (D:\Documents\Projects\f1am3d-games-web-page\node_modules\gamedig\lib\Promises.js:7:25)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
    ```

**Comment by f1ames0ff** [comment]
So I did it like this, because it's the only way it's working:

```ts
exec(
                `gamedig --type ${ type } ${ host }`,
                (error, stdout, stderr) => {
                    if (error) {
                        console.log(`error: ${ error.message }`);

                        return reject();
                    }
                    if (stderr) {
                        console.log(`stderr: ${ stderr }`);

                        return reject(JSON.parse(stderr));
                    }

                    const parsed = JSON.parse(stdout);

                    return resolve(parsed);
                });
```

**Comment by cetteup** [comment]
@f1ames0ff Check the README again. When using gamedig directly in your JS code, you need to pass type, host and port separately as an object. Your valheim example should look like this:

```javascript
const Gamedig = require('gamedig');
Gamedig.query({
    type: 'valheim',
    host: '<myip>',
    port: 2456
}).then((state) => {
    console.log(state);
}).catch((error) => {
    console.log("Server is offline");
});
```

**Comment by mmorrisontx** [comment]
This has gotten pretty off topic, please open a new issue if this continues to be an problem for either case.

**Comment by f1ames0ff** [comment]
@cetteup It's working, thanks!
