### ISSUE TITLE
Minecraft - Filter out empty (00000 id) players

### ISSUE THREAD

**Issue by strongruff** [gamedig/node-gamedig#226]
Players(15) [
  Player {
    name: '§7 []§7§m--------------------------------------------§7[]',
    raw: { id: '00000000-0000-0000-0000-000000000000' }
  },
  Player {
    name: '§7 §9§l| EJDRE MC | TWITCH | 1.16.5 |§6§l §f§l',
    raw: { id: '00000000-0000-0000-0000-000000000000' }
  },
  Player {
    name: '§7   §lMC ServerIP §7:§6 mc.ejdre.cz',
    raw: { id: '00000000-0000-0000-0000-000000000000' }
  },
  Player {
    name: '§7   §lTS3 ServerIP §7:§6 ts3.ejdre.cz',
    raw: { id: '00000000-0000-0000-0000-000000000000' }
  },
  Player {
    name: '§7   §lDISCORD §7:§6 discord.gg/2vJ2nTY',
    raw: { id: '00000000-0000-0000-0000-000000000000' }
  },
  Player {
    name: '§7   §lTWITCH §7:§a www.twitch.tv/ejdre',
    raw: { id: '00000000-0000-0000-0000-000000000000' }
  },
  Player {
    name: '§7',
    raw: { id: '00000000-0000-0000-0000-000000000000' }
  },
  Player {
    name: '§7   §6Info',
    raw: { id: '00000000-0000-0000-0000-000000000000' }
  },
  Player {
    name: '§7   §f§lVerze Serveru: §e1.16.5',
    raw: { id: '00000000-0000-0000-0000-000000000000' }
  },
  Player {
    name: '§7   §f§lHráčů: §e0/30',
    raw: { id: '00000000-0000-0000-0000-000000000000' }
  },
  Player {
    name: '§7   §f§lTyp hry: §a§lSURVIVAL',
    raw: { id: '00000000-0000-0000-0000-000000000000' }
  },
  Player {
    name: '§7   §f§lObtížnost: §c§lHARD',
    raw: { id: '00000000-0000-0000-0000-000000000000' }
  },
  Player {
    name: '§7   §a§lPřipoj se k §bplayer §f...',
    raw: { id: '00000000-0000-0000-0000-000000000000' }
  },
  Player {
    name: '§7',
    raw: { id: '00000000-0000-0000-0000-000000000000' }
  },
  Player {
    name: '§7 []§7§m--------------------------------------------§7[]',
    raw: { id: '00000000-0000-0000-0000-000000000000' }
  }
]

**Comment by mmorrisontx** [comment]
Can you post the full output with --debug? Is the reported player count correct? I wonder if we should just exclude players with `00000000-0000-0000-0000-000000000000` id from the sample output.

**Comment by strongruff** [comment]
> Could you please provide a basic description of the issue and a (test) server you are encountering the issue with?

i practicaly fully described it in the name of the Issue
and server belong to my friend (twitch streamer - Ejdre)
and it is managed by Ejdre's friend on his own dedicated server
that is prolly all i needed to say

**Comment by mmorrisontx** [comment]
We need the ip of the server in order to test against it.

**Comment by strongruff** [comment]
> We need the ip of the server in order to test against it. edit: I guess it's hidden in the scoreboard output

mc.ejdre.cz

**Comment by CosminPerRam** [comment]
Hey, coming back to this quite late.
The second player's name is `§7 §9§l| EJDRE MC | TWITCH | 1.16.5 |§6§l §f§l`, where the `§` character followed by a letter/number represent text styling in Minecraft's text.

This behaviour comes from plugins such as [serverlistmotd](https://dev.bukkit.org/projects/serverlistmotd), which lets you configure custom text when hovering over the players list (or in this case just getting query data).

Example of such behaviour:
![image](https://github.com/gamedig/node-gamedig/assets/7972857/acb2b153-917b-4beb-8a68-bac44479efde)

As one might still want to get this data, I wouldn't find fit to filter players with `id`'s that are '0', also as these plugins could return whatever they want (at least not in the library, this can be easily done after querying the server).
