### ISSUE TITLE
Just a question about Garry's Mod localhost game info "query"

### ISSUE THREAD

**Issue by SirLancelot06** [gamedig/node-gamedig#227]
Sorry if I am using the GitHub issue tracker wrongly I never used so I'm quite new to it and I couldn't find any way to contact any developers of Gamedig.
I just have a simple question.
I try to make a NodeJS Discord bot on a Debian server wich has a Garry's mod server on the same network and computer.
I try to query/poll game info from the GMod server like players and if it is online or not I tried with localhost,127.0.0.1 and numerical public IP address. The GMod server's 27015 port is forwarded people can join and when my friend tried to get info with Gamedig he got the info from other computer but when I try it from the same computer It gives me a "UDP - Timed out error" and I don't know what to do.

This is what I get in the console:

`Error: Failed all 3 attempts
    at QueryRunner.run (/servers/GModBot/node_modules/gamedig/lib/QueryRunner.js:88:21)
Attempt #1 - Port=27015 Retry=0:
Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (/servers/GModBot/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)`
    
Thanks for any help and again sorry if I'm using the issue tracker completly wrong. I just want some help. c: (Sorry if my English is broken I'm not speaking it natively).

**Comment by cetteup** [comment]
Two quick things:
1. Is the GMod server listening on the loopback interface (127.0.0.x)? You can check with `netstat -tulpn` for example.
2. Could you provide the relevant gamedig command/code you are using on the server?

**Comment by SirLancelot06** [comment]
In the netstat -tulpn screen I only have these addresses:

![image](https://user-images.githubusercontent.com/19470659/118642760-020c9800-b7dc-11eb-9cdb-43f429ec5268.png)

There is a TCP = 127.0.1.1:27015 and a UDP = 0.0.0.0:27015

The JS code that I'm using is this:
`const Gamedig = require('gamedig')

Gamedig.query({
    type: 'garrysmod',
    host: 'localhost'
}).then((state) => {
    console.log(state);
}).catch((error) => {
    console.log("Server is offline");
});`

**Comment by SirLancelot06** [comment]
It seemsI fixed my little "issue".

It seems like GMod couldn't automatically listen or get it's local IP address so I gave it directly with this command:
`+ip 192.168.100.30` and now everything works nicely.
![image](https://user-images.githubusercontent.com/19470659/118644817-7ba58580-b7de-11eb-8374-5564bf57deaa.png)

Thanks **catteup** for telling me the loopback ip things and the netstat addresses!
I couldn't have found anything about them by myself and have a big migrane while searching the whole internet thank you very much and sorry for taking your time with this stupid "Issue". :)
