### ISSUE TITLE
Unreal Tournament 4 - Add Support

### ISSUE THREAD

**Issue by dgibbs64** [gamedig/node-gamedig#231]
Request for UT4 Server. It uses port 7778 to query.
I found this python script that gives the query strings. 
Thought you might be able to make more sense of it than me.

https://gist.github.com/maikelwever/5c4ca5f5fa9e72685812

Thank you

**Comment by mmorrisontx** [comment]
The development of UT4 was cancelled. Is there a game you are interested in that actually uses this protocol?

**Comment by dgibbs64** [comment]
Unreal Tournament 4 seems to be the only server that uses port 7778 to query I currently know of. Others seem to have implemented "source" query protocol with UE4 rather than what appears to be the Epic solution. I currently support UT4 server for LinuxGSM but don't have a way to query it.

I understand if you decide not to implement it as there will probably not be many that use it. But the info is available just in case :)

**Comment by mmorrisontx** [comment]
I think the hardest part would probably be finding a server with sufficient uptime to test the protocol. Especially one with players.

**Comment by dgibbs64** [comment]
I can setup a server and provide the address details. I can leave it running for a while of needed.

**Comment by mmorrisontx** [comment]
I downloaded the latest 2017 copy of the game client and captured some query packets, and they look nothing like the ones in the linked python script, and unfortunately the ones from the script don't work anymore. With the query protocol being basically entirely undocumented, I don't think it's worth reverse engineering it again just for it to wind up partially broken anyways.

**Comment by dgibbs64** [comment]
Fair enough. Makes sense to me. Thank you for taking a look at it 🙂👍
