### ISSUE TITLE
Dayz - Any way to query for queued players?

### ISSUE THREAD

**Issue by podrivo** [gamedig/node-gamedig#232]
Hey! I'm trying to get the connecting players in a Valve server, but the players count only returns connected players. I'm looking to show the queue of players for that server.

I tried commenting the line that mentions this, but didn't change anything...
https://github.com/gamedig/node-gamedig/blob/ce4e72849386b5771959de7d6e024cf775090279/protocols/valve.js#L178-L179

Is it possible to also get the connecting players? Thank you!

**Comment by mmorrisontx** [comment]
Unlikely. Some valve games return players that are loading, without a name, but that only takes a few seconds. Most of the connection time for a player is often for fastdl, during which the player isn't actually connected to the server at all.

**Comment by podrivo** [comment]
But the players I want to get are connected to the server, but waiting in a queue.

**Comment by mmorrisontx** [comment]
What sort of server is it? How is the queue enforced? I haven't seen any stock valve games with a join queue.

**Comment by podrivo** [comment]
DayZ servers have queues. You can check this server: [https://www.battlemetrics.com/servers/dayz/11359652](https://www.battlemetrics.com/servers/dayz/11359652)
It's almost guaranteed it's going to have a queue. Max of 50 players playing, but the queue right now is around 17 players, because I check in their discord server.

**Comment by mmorrisontx** [comment]
ah, dayz is a bit of a special egg... it technically implements the valve protocol, but it's not the standard implementation provided by valve.

Regardless, it doesn't look like it provides any info about its queue unfortunately. All the data we can possibly receive from the server is included in the gamedig `raw` subobject (with extras if you add `requestRules: true`), but it seems that all the data it returns only reflects the people that are already online and past the queue.

**Comment by podrivo** [comment]
That's unfortunate... Well, I'll keep digging to see if I can find an answer.
Is this something you consider adding to the library? If so, I'll make sure to let you know if I find something! (:

Thank you for your fast reply! All the best!

**Comment by mmorrisontx** [comment]
Yep, if you find a good solution, we could definitely add it 😄

**Comment by podrivo** [comment]
Found an answer @mmorrisontx! 😄 
You can see the question here: https://github.com/daemonforge/DayZ-UniveralApi/issues/2

So it turns out that this info is not in the A2S_PLAYER query, but from tags in the A2S_INFO query:
https://github.com/gamedig/node-gamedig/blob/ce4e72849386b5771959de7d6e024cf775090279/protocols/valve.js#L107

Response is usually something like this:
```
"tags": "battleye,no3rd,external,privHive,shard,lqs11,etm3.000000,entm4.000000,mod,16:14"
```
So for example:
- **lqs11** = Number is the queue
- **battleye** = Battleye Enabled
- **no3rd** = First Person Only
- **16:14** = Current Game Time
- **etm3.000000** = Day Time Acceleration 3x
- **entm4.000000** = Night Time Acceleration 4x

**Comment by mmorrisontx** [comment]
This is awesome. Glad it's already there ^_^. I'll leave this ticket open in case we have a chance to put parsing for these tags into gamedig itself.

**Comment by podrivo** [comment]
That's awesome, @mmorrisontx!

There's an example in this code, in case it make things easier: 
https://github.com/daemonforge/DayZ-UniveralApi/blob/master/DayZWebService/serverquery.js

```
let keywords = state.raw.tags.split(',');

queue: parseInt(keywords.find(tag => tag.includes('lqs')).replace('lqs', '')),
first_person: keywords.some(tag => tag.includes('no3rd')),
time: keywords.find(tag => tag.includes(':')),
time_acceleration: parseFloat((keywords.find(tag => tag.includes('etm')) || '12').replace('etm', '')) + ", " + parseFloat((keywords.find(tag => tag.includes('entm')) || '1').replace('entm', '')),
day_time_acceleration: parseFloat((keywords.find(tag => tag.includes('etm')) || '12').replace('etm', '')),
night_time_acceleration: parseFloat((keywords.find(tag => tag.includes('entm')) || '1').replace('entm', '')),
battleye: keywords.some(tag => tag.includes('battleye')),
public_hive: !keywords.some(tag => tag.includes('privHive')),
dlc_enabled: keywords.some(tag => tag.includes('isDLC')),
```

**Comment by podrivo** [comment]
Hey @mmorrisontx! That's awesome! Glad we could work together to update the repo! ✨ 

I was wondering, since in DayZ the server `time`, `first_person` and `dlc_enabled` are really used for filtering when joining servers, do you think it's a good idea to add in the library?
