### ISSUE TITLE
EOS - Add Protocol

### ISSUE THREAD

**Issue by MisterRee** [gamedig/node-gamedig#239]
Not sure if it's possible, but as more and more games move to support servers hosted by Epic Online Services (EOS) it would be great if we were able to query them the same way. Thanks.

**Comment by podrivo** [comment]
Hello @MisterRee!

Do you have more info about servers hosted by EOS? A game server list example? Which games are supported by EOS?

Thank you! (:

**Comment by CosminPerRam** [comment]
Support for EOS was added in #402.
If you'd like support for certain new games (or already existing ones to move) that could use EOS, feel free to make a new issue!
