### ISSUE TITLE
How do I change the result for a text?

### ISSUE THREAD

**Issue by tomaslxc** [gamedig/node-gamedig#243]
![image](https://user-images.githubusercontent.com/44044397/132935689-f6779c38-7c80-4bca-93c0-94de9e5f6212.png)
![image](https://user-images.githubusercontent.com/44044397/132935723-f71cf5b7-b6fe-4591-a358-91c927337832.png)

How do I change the result for a text?
example: 1 = Server with password
0 = Server without password

**Comment by mmorrisontx** [comment]
Since this is a generic javascript question unrelated to gamedig, it would probably be better to ask on a javascript help forum or possible https://stackoverflow.com/
