### ISSUE TITLE
Update TF2 protocol

### ISSUE THREAD

**Issue by justkamiii** [gamedig/node-gamedig#245]
https://steamcommunity.com/discussions/forum/14/2974028351344359625/
https://developer.valvesoftware.com/wiki/Server_queries#A2S_INFO

https://steamcommunity.com/discussions/forum/14/2974028351344359625/

**Comment by mmorrisontx** [comment]
Gamedig was prepared for this change before it happened. Are you experiencing issues with the latest version?

**Comment by km-ch** [comment]
> Gamedig was prepared for this change before it happened. Are you experiencing issues with the latest version?

Oh, I see! After researching a little bit more, it seems that my game server was actually down hahaha. The latest update is crashing servers, sadly

**Comment by justkamiii** [comment]
> Gamedig was prepared for this change before it happened. Are you experiencing issues with the latest version?

Oh, I see! After researching a little bit more, it seems that my game server was actually down hahaha. The latest update is crashing servers, sadly. A friend pointed out these links and told me to just create an issue in here. It was pretty stupid of me to just go and make the issue without first doing a Lil bit more research. Sorry, and thanks for replying
