### ISSUE TITLE
Last Oasis - Add support

### ISSUE THREAD

**Issue by dgibbs64** [gamedig/node-gamedig#248]
Please can you add Last Oasis support?

The default query port is 27015 game port is 7777 and the engine is unreal 4. However, I am unable to query the port using protocol-valve. Please let me know if you need any test servers setup for the servers I am requesting and I can send you the ip addresses

**Comment by podrivo** [comment]
Hey @dgibbs64! By any chance, do you have online servers examples so we can test a bit more?
I've found this [server list](https://www.trackyserver.com/last-oasis-server), but there's no query port and unfortunately `27015` is not working.

Thank you!

**Comment by dgibbs64** [comment]
Hi @podrivo Sadly I don't. I have now deprecated Last Oasis from LinuxGSM as the game has been abandoned. So I think this can just be closed.

**Comment by podrivo** [comment]
Yeah, the servers from that servers list have been not updated in 1 year, if you check each one. There's maybe a couple that is currently being updated.

Despite having few players, the game seems to be active: https://steamcharts.com/app/903950

**Comment by CosminPerRam** [comment]
Due to the abandonment of the games development we cannot really add support for this game, I will link a commit mention to this issue.
