### ISSUE TITLE
Type Definitions

### ISSUE THREAD

**Issue by ryansonshine** [gamedig/node-gamedig#250]
I think type definitions would be a nice addition to this library. I'm willing to open up a PR just wanted to make sure I wouldn't be duplicating any work.

**Comment by cetteup** [comment]
There are some basic type definitions in [@types/gamedig](https://www.npmjs.com/package/@types/gamedig), which are exported from https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/gamedig.

They are not complete/not quite up to date though.

**Comment by mmorrisontx** [comment]
Seems like DefinitelyTyped is a better place for this to live for now, since they're better at reviewing and accepting ts merge requests than I am 😅
