### ISSUE TITLE
Issues with the way the library requires files

### ISSUE THREAD

**Issue by utrolig** [gamedig/node-gamedig#251]
By using calls to `fs` and using a text-file for the game protocols, this library is not possible to be used in an electron environment (at least I couldn't figure out how to)

Is this something you're aware of? 
Is it hard to fix?

Thanks!

**Comment by mmorrisontx** [comment]
Is webpack a requirement with electron, or optional? Since electron is backed by node, I'd be surprised if they required you to rebundle your code instead of just distributing it as is.

**Comment by mmorrisontx** [comment]
I'm definitely onboard with making this webpack compatible, especially if games.txt is the only thing standing in the way. Although I'm not thrilled that the best option seems to be to just throw it into a giant text field inside of a js file that can be required.

**Comment by utrolig** [comment]
I think it's a combination of games.txt and using `fs.existsSync` to resolve protocols.

If you're open for freelance work I'd happily pay for you to help me out with getting gameinfo and gamestatus for quake 3 servers. I'm trying to solve it by using pure udp sockets directly from node but I can't really seem to get it working.

**Comment by CosminPerRam** [comment]
Hey, hitting this old issue up as #407 removed the file completely, feel free to reopen this issue if there are any more problems!
