### ISSUE TITLE
New Steam update, outdating the package

### ISSUE THREAD

**Issue by chxlls** [gamedig/node-gamedig#256]
Steam are slowly rolling out what looks like a new layer of protection or something when querying a game server

This new change has caused the package to not be able to get a response back (Timing out)

**Comment by mmorrisontx** [comment]
Gamedig has supported this update for a long time now. Are you using the latest version?

**Comment by chxlls** [comment]
I don't believe so, this update has only just been rolled out. I am using the latest version, still no dice.

The link I had in there was an old one, but they are releasing another type of update like that.

**Comment by chxlls** [comment]
^^ Here is some information on it.. It is from another Game Server Query package but it hold some information

[https://github.com/Austinb/GameQ/issues/581](url)

**Comment by mmorrisontx** [comment]
Both of the 'broken' servers listed in that gameq ticket query flawlessly for me with the latest gamedig. Do you have an example server ip which doesn't work?

**Comment by chxlls** [comment]
Yeah,

garrysmod
139.99.144.121

**Comment by mmorrisontx** [comment]
gamedig does handle the A2S_INFO challenge properly for the server you've given, but then it just never responds to the second packet. Makes me believe there may be a configuration issue specific to this server rather than a gamedig problem, since I know gamedig a2s_info challenge support works on other source servers in the past.

```
$ bin/gamedig.js --type garrysmod --debug 139.99.144.121
Q#0 Starting
Q#0 Protocol: Valve
Q#0 Options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxAttempts: 1,
  port: 27015,
  protocol: 'valve',
  requestRules: false,
  type: 'garrysmod',
  host: '139.99.144.121',
  debug: true
}
Q#0 DNS Lookup: 139.99.144.121
Q#0 Raw IP Address: 139.99.144.121
Q#0 Requesting info ...
139.99.144.121:27015 UDP(52020)-->
Buffer length: 25 bytes
ff ff ff ff 54 53 6f 75 72 63 65 20 45 6e 67 69 6e 65 20 51 75
            T  S  o  u  r  c  e     E  n  g  i  n  e     Q  u
65 72 79 00
e  r  y

139.99.144.121:27015 <--UDP(52020)
Buffer length: 9 bytes
ff ff ff ff 41 7b d4 ef 38
            A  {        8

Q#0 Registered RTT: 262ms
Q#0 Received full packet
Q#0 Received 0x41 expected 0x49
Q#0 Received new challenge key: 0x38efd47b
Q#0 UDP send finished by callback
139.99.144.121:27015 UDP(52020)-->
Buffer length: 29 bytes
ff ff ff ff 54 53 6f 75 72 63 65 20 45 6e 67 69 6e 65 20 51 75
            T  S  o  u  r  c  e     E  n  g  i  n  e     Q  u
65 72 79 00 7b d4 ef 38
e  r  y     {        8

Q#0 UDP timeout detected
```

**Comment by chxlls** [comment]
Ahh okay, I am good friends with the server owner. Anything specific I should go back and say?

**Comment by chxlls** [comment]
New information @mmorrisontx 

When I run a query on the Rust server first then try the GMOD one, it works?

rust
139.99.144.121

and then try the gmod one

**Comment by mmorrisontx** [comment]
Same happens when I try locally. Since the rust and gmod servers are totally unrelated, and gamedig is stateless between queries, and they operate on different ports, the only explanation is something weird going on on your server side. Probably some weird anti-ddos or firewall rules, either on the hosting machine or configured by your ISP / hosting provider.

**Comment by xLeviNx** [comment]
Very likely he hasn't updated his settings to adjust to the new queries. 

https://steamcommunity.com/discussions/forum/14/2974028351344359625/

**Comment by mmorrisontx** [comment]
Settings shouldn't need to be adjusted if the machine is configured properly. Although, disabling the new challenge response may solve this issue indirectly.

**Comment by xLeviNx** [comment]
> 

Well thats with the assumption that the user has adjusted it in accordance to the new query. Any old gameservers that have been running for years have had to adjust it, including plugins and queries

**Comment by mmorrisontx** [comment]
I don't think there's any action needed in gamedig for this ticket. Please reopen if I've missed something.
