### ISSUE TITLE
added satisfactory in games

### ISSUE THREAD

**Issue by derecklefou** [gamedig/node-gamedig#260]
Hello, I am contacting you to find out if it is possible to put satisfactory in list of games available from gamedig it is a game available on steam/epic games

**Comment by mmorrisontx** [comment]
I don't believe that satisfactory servers provide a query api. Best resource I could find was this feature request: https://questions.satisfactorygame.com/post/61834537831c852052359e9c

**Comment by nafeasonto** [comment]
NM i made a PUSH notification with PowerShell to push it to the Kuma
