### ISSUE TITLE
Problem Cs 1.5 not supported

### ISSUE THREAD

**Issue by FolksyLegend** [gamedig/node-gamedig#266]
Failed to get server information cs 1.5
Server is RUN!
gamedig --type cs15 62.140.250.16 --port 27015
Consol log 
{"error":"Failed all 1 attempts"}
Please tell me how to fix(

**Comment by mmorrisontx** [comment]
Are you sure a server is still running on this IP? Seems like it was a server from like 8 years ago...

**Comment by mmorrisontx** [comment]
Oh, we may actually have ripped out the ancient goldsrc protocol support when steam made the big push to fully migrate all the old games over to the source query engine.

**Comment by mmorrisontx** [comment]
This is fixed in gamedig 4.0.2 https://github.com/gamedig/node-gamedig/commit/07c7eca2623ad0fca859683921c6a16371a06e75
