### ISSUE TITLE
Ground Breach support?

### ISSUE THREAD

**Issue by NFrecks** [gamedig/node-gamedig#267]
I dont know how to request or what information I need to give.

**Comment by mmorrisontx** [comment]
Does it work if you use protocol-valve as the game? What's the default game port and query port?

**Comment by NFrecks** [comment]
ports
7777 UDP
27015 UDP
with -valve protocol it shows all green checks on sb!status but the broadcast says server offline. 
the game is running on a rented server. I have been given admin access to work on getting bot set up.

**Comment by mmorrisontx** [comment]
The query works properly from my machine:
```
bin/gamedig.js --type protocol-valve 69.41.1.247:27015
{"name":"Frag Friends Tactical (Non CTE)","map":"SmallTown","password":true,"raw":{"protocol":17,"folder":"groundbranch","game":"Ground Branch","appId":16900,"numplayers":0,"numbots":0,"listentype":"d","environment":"w","secure":0,"version":"1.0.0.0","steamid":"90156684023359489","tags":["nv1032132701","mnTerroristHunt","sp0","wl0"]},"maxplayers":16,"players":[],"bots":[],"connect":"69.41.1.247:7777","ping":82}
```

If you are using a discord bot, you should contact the bot owner. This is the support board for node-gamedig, the library only.

**Comment by NFrecks** [comment]
> The query works properly from my machine:
> 
> ```
> bin/gamedig.js --type protocol-valve 69.41.1.247:27015
> {"name":"Frag Friends Tactical (Non CTE)","map":"SmallTown","password":true,"raw":{"protocol":17,"folder":"groundbranch","game":"Ground Branch","appId":16900,"numplayers":0,"numbots":0,"listentype":"d","environment":"w","secure":0,"version":"1.0.0.0","steamid":"90156684023359489","tags":["nv1032132701","mnTerroristHunt","sp0","wl0"]},"maxplayers":16,"players":[],"bots":[],"connect":"69.41.1.247:7777","ping":82}
> ```
> 
> If you are using a discord bot, you should contact the bot owner. This is the support board for node-gamedig, the library only.

ok, sry about that. i said something to somone in the bot channel and they said i should request on this site.... oof
