### ISSUE TITLE
V-Rising - Add Support

### ISSUE THREAD

**Issue by cyphercolt** [gamedig/node-gamedig#282]
Would it be possible to add support for the new game V-Rising? 
https://store.steampowered.com/app/1604030/V_Rising/
https://github.com/StunlockStudios/vrising-dedicated-server-instructions

**Comment by cyphercolt** [comment]
Server IP: 184.160.214.72
Port: 27015
Protocol: UDP

**Comment by cyphercolt** [comment]
Hah I got it to work using the valheim GamedigQuery

**Comment by jaune** [comment]
@cyphercolt Thanks.
