### ISSUE TITLE
Support for V-Rising (valheim protocol not working)

### ISSUE THREAD

**Issue by Murgator** [gamedig/node-gamedig#285]
I tested the valheim protocol for V-Rising servers but it does not work for some servers:

WORK:
ip: 184.160.214.72
port: 27016
query_port: 27015

NOT WORKING:
ip: 103.47.133.171
port: 9877
query_port: 9876

ip: 152.249.166.90:27016
port: 27016
query_port: 27015

ip: 177.54.150.119
port: 27074
query_port: 27073

https://store.steampowered.com/app/1604030/V_Rising/
https://github.com/StunlockStudios/vrising-dedicated-server-instructions

Help would be appreciated thanks in advance !

**Comment by kferrano** [comment]
send your ServerHostSettings.json (V-Rising) and servers.json (Bot)

**Comment by Murgator** [comment]
thank you kferrano but now it seems to be working...
