### ISSUE TITLE
Arma Reforger (2022) - Add support

### ISSUE THREAD

**Issue by a-sync** [gamedig/node-gamedig#286]
This is what i came up with:
`armareforger|ARMA Reforger (2022)|valve|port=2001,port_query=17777`
It didn't work.. :) 

The protocol might be closer to dayz then arma3 since they both use the enfusion engine.

**Comment by a-sync** [comment]
added in #366

**Comment by CosminPerRam** [comment]
Thanks for pointing this out (:
