### ISSUE TITLE
Problem with Discord

### ISSUE THREAD

**Issue by dudekm** [gamedig/node-gamedig#299]
Hi.
I have a problem with retrieving data from the Discord server.

Command:
```
gamedig --type discord 651278179348119553
```

Result:
```
C:\node-app\npm\node_modules\gamedig\bin\gamedig.js:31
    const split = target.split(':');
                         ^

TypeError: target.split is not a function
```

Here you have the working URL: https://discordapp.com/api/guilds/651278179348119553/widget.json
NodeJS version: 18.6

Am I doing something wrong? @mmorrisontx

**Comment by bbashy** [comment]
As per the docs, you need to supply the Server ID in the guidId param.

`gamedig --type discord --guildId 651278179348119553`
