### ISSUE TITLE
say server is offline but it's online FiveM

### ISSUE THREAD

**Issue by WhyimzackDev** [gamedig/node-gamedig#301]
Tested with my own fivem server and it works but when I try with the server I want it doesn't work. I suspect it's because the server is protected with cloudflare

**Comment by xCausxn** [comment]
Likely to be that it's behind cloudflare, probably being detected as a bot.

You can allow specific IPs through the cloudflare firewall in dashboard, so I would check there first.

**Comment by CosminPerRam** [comment]
Will close this as its probably just Cloudflare firewall doing some action, feel free to re open if this reoccurs.
