### ISSUE TITLE
Not querying fivem server

### ISSUE THREAD

**Issue by BigBl0b** [gamedig/node-gamedig#302]
The server was up as I was on the server at the time, so it wasn't that.

I temp disabled the firewall altogether and it still wouldn't query through, so it wasn't that.

So i'm kinda at a loss as to why it won't work.

IP: 148.251.8.17:30120

**Comment by xCausxn** [comment]
I just tested locally from my local network and also my server in Germany. The query seems to work fine with the latest release as shown with the screenshot.

<img width="1683" alt="image" src="https://user-images.githubusercontent.com/1427375/188315356-715811a8-3ec5-4123-b4be-874a69381912.png">

Are you able to test with:
`npx gamedig --type fivem --host 148.251.8.17 --port 30120`

Also what version of node and gamedig are you using in your code?

**Comment by BigBl0b** [comment]
How can I find out what version i’m using?

**Comment by BigBl0b** [comment]
This is what I get running that command - https://prnt.sc/5NYzOJXDFZc7

**Comment by xcpep** [comment]
The query is working fine for me as well. The IP you are making the request from may be blocked at the server or higher level which is preventing you from sending the request.

**Comment by BigBl0b** [comment]
The IP is fine, and I have just worked out it is a me issue.

However I can query to my garrysmod and minecraft servers fine, but ANY fivem issues seems to not want to work.

it says “Q#0 TCP Closed” - Any idea why it does this for fivem and none of the other servers or games?

**Comment by BigBl0b** [comment]
@xCausxn

**Comment by xCausxn** [comment]
As it looks like it's not a problem with the library, and multiple people seem to be getting successful responses.

1) increase the timeout when querying?
2) you are getting blocked by that server for X reason
3) run the script on a vps outside your network as that will probably mitigate any residential issues.

As we can't seem to replicate it ourselves this is very much a case of grasping at straws
