### ISSUE TITLE
Gamedig not working on ubuntu server

### ISSUE THREAD

**Issue by krzychuL1** [gamedig/node-gamedig#305]
I installed gamedig on ubuntu and when im trying to use it to mta sa server it won't work. Someone can help me?

**Comment by cetteup** [comment]
Could you post an example Server you cannot query? Is it your own server?

**Comment by krzychuL1** [comment]
Hello, it's only on ubuntu it cannot send information about mta server. I have installed gamedig but on windows it works. I think i have the newest version of nodejs. Server what im trying to query in ubuntu
Ip: 137.74.7.181
Port: 22110
Gamedig for me only work on windows :/

**Comment by cetteup** [comment]
Are you getting an error on the Ubuntu machine? Or does the query just time out?

**Comment by krzychuL1** [comment]
i got this error "{"error":"Failed all 1 attempts"}"
Screen: ![image](https://user-images.githubusercontent.com/73475739/205111674-8e409a45-93ab-44a5-9d2b-28725977ee0e.png)
VPS machine: Oracle cloud

**Comment by cetteup** [comment]
It's not uncommon for game server owners/providers to block known hosting providers. No real player would ever connect from the Oracle cloud.

Try a few different servers, this likely is not issue with Ubuntu or gamedig.

**Comment by krzychuL1** [comment]
I need it for discord bot in a status but it won't work on ubuntu but on windows it's working. Maybe oracle cloud blocking port or something but im onlockong it but it doesn't work :/

**Comment by cetteup** [comment]
@krzychuL1 Did you get it to work?

**Comment by krzychuL1** [comment]
I kept trying to fix it but gave up for now

**Comment by mmorrisontx** [comment]
If a game server host prevents your server provider from sending requests to their IPs, there's really not much you can do aside from host your service somewhere else.

**Comment by CosminPerRam** [comment]
Hey, closing this as this probably is a network blocking problem on your end, which we can't do stuff about it, if you would like to contest this or have any more questions feel free to reopen this issue.
