### ISSUE TITLE
Add method for getting list of supported server types

### ISSUE THREAD

**Issue by skylord123** [gamedig/node-gamedig#308]
I manage the package [node-red-contrib-gamedig](https://flows.nodered.org/node/node-red-contrib-gamedig) which uses this library under the hood (pretty obvious based on the name). This allows people to use a GUI and functional block programming to wire together something quickly. A good example of what I use it for is querying my game servers and auto restarting them if they fail X times as well as tracking the player counts. Node-RED made this extremely easy to wire together without much programming:
![image](https://user-images.githubusercontent.com/3412313/208210667-155ff3bf-7585-4ac4-a927-bb1023c08958.png)

Now the issue I currently have is when someone sets up the gamedig node in Node-RED they give it options:
![image](https://user-images.githubusercontent.com/3412313/208210430-56705c13-8e8b-4c4b-a0fb-ec8968110822.png)

I would like to make the Server Type input in that page use an actual list of available server types provided from the library. I had some code that was parsing it from the readme (really gross, I know) and it seems that stopped working recently.

Can we get a method added so I can fetch these and provide them to the end user? This way I don't have to manually add them in as you do or rely on my horrible readme scraping method.

Thanks for the great library by the way, has been really handy!

**Comment by magynhard** [comment]
Did you think about parsing the games.txt in the project root? So you have at least all the time a proper format to parse and not to extract data from a randomly changed README file.

**Comment by skylord123** [comment]
@magynhard I don't know how I missed this. This is great. Thanks!
