### ISSUE TITLE
Add Vintage Story support

### ISSUE THREAD

**Issue by n0k1234** [gamedig/node-gamedig#328]
Any? :) Thanks, i used the bot before in other games and i love it.

**Comment by cetteup** [comment]
Some quick research suggests Vintage Story may not offer any sort of query protocol. There is a mod that offers an HTTP endpoint, see https://mods.vintagestory.at/theserverstats.

However, I don't think that is something worth adding to gamedig. If you have a server with the mod installed, you can already easily get server details as JSON.

**Comment by CosminPerRam** [comment]
They also provide master server info here:
https://masterserver.vintagestory.at/api/v1/servers/list
