### ISSUE TITLE
Add support for Factorio

### ISSUE THREAD

**Issue by undercoverturbo** [gamedig/node-gamedig#331]
Hello there,

I would love to see support for Factorio Servers in the future.

Thanks for the awesome project,
undercoverturbo

**Comment by CosminPerRam** [comment]
I can't seem to find if the game has a query protocol, and it seems it does not.
Although there is a master server that keeps track of servers, we could query it but not server directly.

**Comment by benlucas** [comment]
You can query a factorio server directly using the [RCON](https://developer.valvesoftware.com/wiki/Source_RCON_Protocol) protocol and issue [console commands](https://wiki.factorio.com/Console) to get info such as number of players online.

Working examples can be found here [rcon-cli](https://github.com/gorcon/rcon-cli) or using a library such as [rcon-client](https://github.com/janispritzkau/rcon-client) with something like
```javascript
import {Rcon} from "rcon-client";
const rcon = await Rcon.connect({
    host: "<IP>", port: 27015, password: "<RCON_PASS>"
})
console.log(await rcon.send("/players online"))
```
Hope that helps!

**Comment by CosminPerRam** [comment]
Apparently there is a way!
Querying the master server for the list of all servers requires a token (you must have the game purchased), but they also provide a method to get info about a specific server, check this out:
https://multiplayer.factorio.com/get-game-details/195.216.56.235:32101
I don't exactly know if all servers register on the master, I guess not, but this is a partial solution. Could you check if you can query your server this way?

Hmm, RCON is also an option to be considered, thanks.

**Comment by podrivo** [comment]
@CosminPerRam I've tried some servers from this list: https://dservindex.com/, with the URL you've provided and some responded with server info, but some only with this message:

```js
{
"message": "no game for given host_address"
}
```
