### ISSUE TITLE
UDP timeout detected: sometimes it works sometimes it doesn't

### ISSUE THREAD

**Issue by Murgator** [gamedig/node-gamedig#334]
Hi everyone, I have this problem on a Rust server which is nevertheless online: 149.202.88.84:28316 while is online here: https://rust-servers.net/server/162825/

![497b5644879240a91d8417890db87f2f](https://user-images.githubusercontent.com/38978895/219001014-4026102c-1fec-4cb8-bb6b-f5c36bbd2254.png)

Thank you for your help

**Comment by Murgator** [comment]
now it works it's strange maybe that the name of a player does not pass ?

![925b29204b34e8e66c798d48dd24e02d](https://user-images.githubusercontent.com/38978895/219004073-ba1ebe35-685d-431a-a2cf-b1a982f288cf.png)

**Comment by CosminPerRam** [comment]
Hey, do you still have problems regarding timeouts?
This might be due to, amongst many other reasons, packets being dropped on your side of the connection.

**Comment by podrivo** [comment]
@Murgator Sometimes servers can timeout a query for many reasons. You can try to add `maxAttempts` and `givenPortOnly` to your query, so that you always get a proper response.

I'm using this and I always get a response:

`gamedig --type rust --maxAttempts 10 --givenPortOnly 149.202.88.84:28316`

**Comment by CosminPerRam** [comment]
Closing this issue as OP didn't responded in a while now and I do not think this is a persistent issue, most likely a client/server latency/packet drops.
Feel free to reopen if something comes up!
