### ISSUE TITLE
Add support for querying BeamMP Servers

### ISSUE THREAD

**Issue by Firav** [gamedig/node-gamedig#340]
Howdy y'all.

I'd like to add support for pinging and retrieving information from BeamMP servers.
I've found the following post about it written in Powershell: https://www.flyinghyrax.net/posts/beammp-server-list/
Whats important to note from that post is that the API URL has changed from https://backend.beammp.com/servers to https://backend.beammp.com/servers-info
Looks to be all parsed in json.

Thanks!

**Comment by CosminPerRam** [comment]
Hey, hitting this old issue!
As mentioned in the linked PR, i haven't found a way to query the server directly, but I've added the master server way you linked, if something comes up, don't hesitate to reopen (:
