### ISSUE TITLE
Please add creativerse to monitoring 

### ISSUE THREAD

**Issue by regchanuk** [gamedig/node-gamedig#343]
currently using Csgo config seems to work if this helps 
 
 but here is ports it uses  officially    the game is called creativerse 

![image](https://github.com/gamedig/node-gamedig/assets/46360316/81f0d0b2-b171-43f2-ac0e-c221ff3e7b45)

**Comment by CosminPerRam** [comment]
Sure thing but could you also link a few game servers to test that the query works?
> currently using Csgo config seems to work if this helps

Meaning it uses the Valve Server Query Protocol, which is already supported, should be easy to add.

**Comment by regchanuk** [comment]
gs1.regchan.uk

with following ports 26901 26904 26906 26907 26913 26916 26919 26922

**Comment by CosminPerRam** [comment]
I don't seem to get any responses, are you sure the ports are open?

**Comment by regchanuk** [comment]
im using query ports for this

**Comment by regchanuk** [comment]
![image](https://github.com/gamedig/node-gamedig/assets/46360316/5336de82-d941-4ef6-9878-d2c881e17eb7)
![image](https://github.com/gamedig/node-gamedig/assets/46360316/dd2f9b60-f110-4e1a-86fb-5dada7264400)
im using uptime kuma uptime.regchan.uk

**Comment by regchanuk** [comment]
heres what settings i used for my monitoring 
![image](https://github.com/gamedig/node-gamedig/assets/46360316/1552d0c0-e355-4029-bfe8-cff3b5b808e7)

**Comment by regchanuk** [comment]
im using query ports for this game

**Comment by regchanuk** [comment]
https://uptime.regchan.uk/api/badge/8/status

**Comment by regchanuk** [comment]
[https://uptime.regchan.uk/api/badge/8/status](img)

**Comment by CosminPerRam** [comment]
Added! Thanks for the suggestion and server probe. It will be available in the next library release, after that Uptime Kurma has to update the gamedig dependency and also to release a version on their end to make it available to you.
