### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by sahara101** [gamedig/node-gamedig#346]
Thank you for adding sonsoftheforest. 
I am trying to add it to gethomepage, but it says game name unknown. Do they have to update their code for this to work?

Thanks!

**Comment by cetteup** [comment]
Yes, they most likely have to actively update to the new version.

**Comment by CosminPerRam** [comment]
As @cetteup said, they still are on `4.0.6` whereas the game was added in `4.0.7`:
https://github.com/benphelps/homepage/blob/494a1c50d5c17b3b6e91501ffc27def4c5eeb7c9/package.json#L19
