### ISSUE TITLE
DayZ request rules weird response

### ISSUE THREAD

**Issue by podrivo** [gamedig/node-gamedig#347]
Hello! I was using gamedig to query a DayZ server, but the mods section response is super weird, with unusual chars.

Here's what I queried:

```gamedig --type dayz 189.127.164.246:2305 --pretty --requestRules```

And the response I got:

```json
"dayzMods": [
      {
        "unknown": 2643451837,
        "workshopId": 1326907393,
        "title": "igemZ_NoBase_Clothing؆��\u0004ztM�\u0007DogtagsS�q�\u0004�J<�\u0013OrigemZ Core NoBase�=�w\u0004��8m\rFlipTransportz��\u000e\u0004V8�\u0014XtraVanilla Cl"
      },
      {
        "unknown": 1768453231,
        "workshopId": 982280046,
        "title": "R\u0004���\u0016Advanced Weapon Scopes��r�\u0004-�\u001d`\u0015Easy Signs [by Cl0ud]裞k\u0004\u0011�}�\u000eMortys Wea"
      },
      {
        "unknown": 1936617328,
        "workshopId": 3291542156,
        "title": "\u0000\b'k"
      },
      {
        "unknown": 1852397330,
        "workshopId": 1920234340,
        "title": "deClothingϹ�\u0004\u0004��\\\u0013Community Framework�\r�\u0004T��l\rVPPAdminTools\u000e\nADM-Server\u000bcftoolsRoot\u0007Cl0udV3\u0004dayz\nDayZR"
      },
      {
        "unknown": 1769173877,
        "workshopId": 1868957281,
        "title": "apo\u0006Inkota\u000eJacob_Mango_V3\nliquidrock\u0003TTC\u0003VPP\tWardog.v3\fWindstrideV2\u0002XV\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
      }
    ]
  ```
  
  Not sure what is happening. Thoughts?
  Thank you!

**Comment by podrivo** [comment]
Well, the error went away by itself. I wonder if it was a mistake done by the server owner. Will close this, since it was a total random bug and not possible to replicate anymore. Thank you!

**Comment by CosminPerRam** [comment]
Hey, I was just checking the problem right now.
> Well, the error went away by itself.

Yeah, I see just normal string titles now.

Parts like this: `\u0004` are called Unicode characters, but the problem is that they are non-printable control characters. Most likely these title contained those characters for only they know what reason, I don't think this is a protocol problem and now that I can't reproduce a response packet like yours I can't really look much into it.

**Comment by podrivo** [comment]
Thank you so much for having the time, @CosminPerRam!
