### ISSUE TITLE
CS2 Support

### ISSUE THREAD

**Issue by mikedrugs** [gamedig/node-gamedig#356]
how do we query cs2 servers? seems to not work using the "csgo" mode

**Comment by CosminPerRam** [comment]
I have asked some time ago the steam support for this information, here is what they replied:
![image](https://github.com/gamedig/node-gamedig/assets/7972857/629806bc-ac08-4f89-a903-1dfc3b80ca0e)
So, its coming soon I guess, we could leave this issue open for when this gets sorted out.

**Comment by CosminPerRam** [comment]
Now that CS2 is released, I have made a server using [this](https://www.reddit.com/r/GlobalOffensive/comments/16asst1/cs2_how_to_create_a_prac_server_with_your_friends/) guide (dedicated servers are also available now).
![image](https://github.com/gamedig/node-gamedig/assets/7972857/bd6494de-7e8b-410d-8ec1-fe3e27992ef4)
Also as it seems that csgo got replaced entirely by cs2, we'll need to rename its game name and id.

**Comment by bbashy** [comment]
It's still possible to run/play CSGO. Please make a new game entry for it so I don't have to use `protocol-valve`.
