### ISSUE TITLE
Update game ids to follow a standard

### ISSUE THREAD

**Issue by CosminPerRam** [gamedig/node-gamedig#374]
## What are game ids
Game ids are important lowercase alphanumeric string that we use when specifying a Game.
Currently, there is no standard on how an ID is made. 
In #371 I said "lets dont make 2-characters ids anymore" because I didn't thought that id represented the game name, and in other pr's for adding games support, the author decided the game id however they wanted (because there are no rules for this).

## What could be done
This issue suggests applying [rust-GameDig](https://github.com/gamedig/rust-gamedig)'s id system added in the [contributing](https://github.com/gamedig/rust-gamedig/pull/108) pr.

## Problems
Although it is stated (at the time of making this issue) in the rust-GameDig's readme that "Warning: This project goes through frequent API breaking changes [...]" this is not done so here, the new ID system will break a bunch of ids and although the next release is a major one, breaking changes could be done, but are not preferred.

One solution for this would be to keep the old ids and add the new ones (until another major version comes), but I haven't verified yet if there are any new-old colliding ones (for example, a new game's id would be `ase` but there is already an old id `ase`, so we cant have both), if this would be possible, I guess its the way to go.

This issue keeps track on deciding what to do about this manner.

**Comment by dgibbs64** [comment]
Totally agree with this. Setting a standardised naming convention and documenting it will be massively helpful. To reduce possible conflict longer names might be best e.g `americasarmy3` however you also run into issues such as `csgo` which would be too long e.g `counterstrikeglobaloffensive`.

with LinuxGSM I use shortnames https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/data/serverlist.csv and havnt had too many issues. The longest shortname used is 8 characters.

**Comment by podrivo** [comment]
Was this issue addressed with this pull (https://github.com/gamedig/node-gamedig/pull/415)?

**Comment by CosminPerRam** [comment]
Not entirely, there are a few that fails (see CI) and I was thinking on providing a 'translation layer' between the old and new ids (#435 helps a lot regarding this, but I just didn't had the time lately).

**Comment by podrivo** [comment]
PR with new ids and translation layer merged https://github.com/gamedig/node-gamedig/pull/496
ID testing issue over at https://github.com/gamedig/rust-gamedig/issues/184

**Comment by CosminPerRam** [comment]
Fully compliant as per [331d7bb](https://github.com/gamedig/node-gamedig/commit/331d7bbc538df0b87971ab8a797c41cf98d2e48a).
