### ISSUE TITLE
tracking: Deno UdpSocket.unref

### ISSUE THREAD

**Issue by Douile** [gamedig/node-gamedig#378]
https://github.com/denoland/deno/issues/20138

When unref is supported in Deno we can remove the hacky fixes from #362.

**Comment by CosminPerRam** [comment]
Deno `1.39.2` got released which includes added ref/unref for UDP in [Deno#21777](https://github.com/denoland/deno/pull/21777), I think it would be safe to remove the hacky fixes and mention that the Minimum Supported Deno Version is `1.39.2`.
