### ISSUE TITLE
Support for open.mp

### ISSUE THREAD

**Issue by ReshiramZekrom1** [gamedig/node-gamedig#388]
**What is this feature about?**
Adding [open.mp](https://github.com/openmultiplayer/open.mp) support to gamedig

**Additional context/references**
open.mp is currently an improved version of SA-MP, made entirely from scratch and open-source. Even their web page with the server fetcher is open-source. I'll link the repository [here](https://github.com/openmultiplayer/web/tree/master/app) because maybe it could be of some use.

Thanks

**Comment by CosminPerRam** [comment]
Some research will be required to add support for the game (meaning low priority), the project seems very interesting.

**Comment by ReshiramZekrom1** [comment]
> Some research will be required to add support for the game (meaning low priority), the project seems very interesting.

Thanks for the reply! 

I've found out they use the same [query mechanism](https://sampwiki.blast.hk/wiki/Query_Mechanism#Response_from_c) that SA-MP uses except for the "d" packet which isn't implemented (SA:MP servers got DoS attacked with it apparently). Anyways the "c" packet is working although it isn't possible to get the player ID and the score with it.

**Comment by CosminPerRam** [comment]
Hey, it seems that they do respond to that query (queried random servers from the server list on their website), do you have any references of this not working (maybe where has been discussed about it?).
I linked the support PR to this issue, I will merge it when this matter gets resolved.

**Comment by ReshiramZekrom1** [comment]
The server doesn't respond to the "[d query](https://github.com/gamedig/node-gamedig/blob/17c351fb4bc5e32d5426e6ca9cc55c67589531ff/protocols/samp.js#L54)" because that request is not supported. With gamedig the server results online but you cant get the current players list. If you replace 'd' with the 'c' in that line

**Comment by CosminPerRam** [comment]
Hmm, but its weird because the server are responding to it, so I guess its normal behaviour?
Query with the 'd' query enabled on a server from their master server:
![image](https://github.com/gamedig/node-gamedig/assets/7972857/4c2bbfad-9ed5-4ad8-8d00-da44bd7627e1)
Without that query:
![image](https://github.com/gamedig/node-gamedig/assets/7972857/21795265-5be0-4f2a-bdfc-f9a459762cad)

Regarding the second screenshot, gamedig does not query with the c/d packet if on the server are more than 100 players (as the server wont respond for possible the reason that you stated).

**Comment by ReshiramZekrom1** [comment]
> Hmm, but its weird because the server are responding to it, so I guess its normal behaviour? Query with the 'd' query enabled on a server from their master server: ![image](https://user-images.githubusercontent.com/7972857/279197424-4c2bbfad-9ed5-4ad8-8d00-da44bd7627e1.png) Without that query: ![image](https://user-images.githubusercontent.com/7972857/279197543-21795265-5be0-4f2a-bdfc-f9a459762cad.png)
> 
> Regarding the second screenshot, gamedig does not query with the c/d packet if on the server are more than 100 players (as the server wont respond for possible the reason that you stated).

I've been using gamedig for years now on my Discord bot and it tracks my San Andreas Multiplayer server. It updates the player lists in a specific channel every x seconds. No issues when the server was on SA-MP. Once I've moved on open.mp, I couldn't update the player list anymore.

I've managed to resolve it by editing the protocol (just swapped the "d" package with the "c" package). But just now, while I was replying to you, I've noticed that the whole "samp.js" file, which I didn't update since at least one year is quite different from the one I had.
I've finally updated it with the latest one here on github and the players' list is working even without changing the protocol.

I'm sorry if I've wasted your time, I should had gave it a try to this before opening the issue. Thank you!

**Comment by CosminPerRam** [comment]
That's alright, I'm happy it works as expected (:
