### ISSUE TITLE
feat: Add support for The Front

### ISSUE THREAD

**Issue by jammsen** [gamedig/node-gamedig#393]
**What is this feature about?**
Please add support for the new game "The Front".

**Additional context/references**
This game uses one SteamQueryPort with 27015 and 3 game ports 5001-5003. Documentation is really sparse but there this might help: https://xgamingserver.com/blog/how-to-create-the-front-dedicated-server/ - If you need more infos please let me know.

**Comment by CosminPerRam** [comment]
Was a quick add as it uses standard stuff, please state if any problems arises!

**Comment by jammsen** [comment]
Hey @CosminPerRam - Sorry im fairly new to Node.JS as a developer again, i know thats not your problem, but could you please help me out and give me a hint how i can accesss this code as an npm while you dont published a new package on https://www.npmjs.com/package/gamedig - I would love to test this.

**Comment by CosminPerRam** [comment]
Hey, for stuff like this the [Discord Server](https://discord.gg/NVCMn3tnxH) is open to help (if you got a Discord account).

But if not, [this guide](https://www.warp.dev/terminus/npm-install-from-github) seems to be what you want, shortly said:
Instead of `npm install gamedig`, for github repositories you would do: `npm install https://github.com/gamedig/node-gamedig`, but this comes with a problem, what if I push to master a breaking/broken change and you reinstall your packages? for this you reference a commit hash (I'll give an example as the latest commit of writing this): `npm install https://github.com/gamedig/node-gamedig#da7a4a6334f398f8cdc703565b36913887d2393b` (referenced commit is this [one](https://github.com/gamedig/node-gamedig/commit/da7a4a6334f398f8cdc703565b36913887d2393b)).

**Comment by jammsen** [comment]
Hey, thanks i will read the article still but i think i understand what you mean, again im very rusty in Node.JS and NPM again, im learning again, so thanks for helping me out. I will join the Discord for sure, thanks for mentioning it.

**Comment by CosminPerRam** [comment]
You'll manage! Best of luck and have fun meanwhile.

**Comment by jammsen** [comment]
Support does not seem to be working for me:

```
~/Desktop/development/gamedig-test
$ npx gamedig --debug --type thefront jammsen.de:27015
Q#0 Starting
Q#0 Protocol: valve
Q#0 Options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxAttempts: 1,
  ipFamily: 0,
  protocol: 'valve',
  requestRules: false,
  type: 'thefront',
  host: 'jammsen.de',
  port: 27015,
  debug: true
}
Q#0 DNS Lookup: jammsen.de
Q#0 Standard Resolve: jammsen.de
Q#0 Found address: 148.251.89.181
Q#0 Requesting info ...
148.251.89.181:27015 UDP(56367)-->
Buffer length: 25 bytes
ff ff ff ff 54 53 6f 75 72 63 65 20 45 6e 67 69 6e 65 20 51 75
            T  S  o  u  r  c  e     E  n  g  i  n  e     Q  u
65 72 79 00
e  r  y

Q#0 UDP timeout detected
Q#0 Query failed with error Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (file:///C:/Users/br-w10-pc/Desktop/development/gamedig-test/node_modules/gamedig/lib/Promises.js:7:18)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
Error: Failed all 1 attempts
    at QueryRunner.run (file:///C:/Users/br-w10-pc/Desktop/development/gamedig-test/node_modules/gamedig/lib/QueryRunner.js:90:17)
    at async Gamedig.query (file:///C:/Users/br-w10-pc/Desktop/development/gamedig-test/node_modules/gamedig/lib/index.js:11:12)
Attempt #1 - Port=27015 Retry=0:
Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (file:///C:/Users/br-w10-pc/Desktop/development/gamedig-test/node_modules/gamedig/lib/Promises.js:7:18)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

~/Desktop/development/gamedig-test
$ npx gamedig --type thefront jammsen.de:27015
{"error":"Failed all 1 attempts"}

~/Desktop/development/gamedig-test
$ npx gamedig --type thefront jammsen.de:27015
{"error":"Failed all 1 attempts"}

~/Desktop/development/gamedig-test
$ npx gamedig --type thefront jammsen.de:5001
{"error":"Failed all 1 attempts"}

~/Desktop/development/gamedig-test
$ npx gamedig --type thefront jammsen.de:5002
{"error":"Failed all 1 attempts"}

~/Desktop/development/gamedig-test
$ npx gamedig --type thefront jammsen.de:5003
{"error":"Failed all 1 attempts"}
```

I have a The Front Dedicated Server running with default settings.
Ports are:
* QueryPort: 27015
* Port: 5001
* BeaconPort: 5002
* Port: 5003
Not sure what the not named ports do, but they need to be passed throught the FW.

**Comment by CosminPerRam** [comment]
Hey, I've followed [this guide](https://xgamingserver.com/blog/how-to-create-the-front-dedicated-server/) to make my server.
Are you sure you've configured your ports as the ones mentioned ones? Is your host available locally? If not, is port forwarding done right?

**Comment by CosminPerRam** [comment]
Just for history reference, we have discussed this problem over the Discord server, turns out OP had some firewall issues, works as expected now.

**Comment by jammsen** [comment]
Yes i had somehow assinged a port 27015 double, after i changed that port to 27022 another SteamQueryPort in range it works instantly. Was down to me and my IPFire instance. Thanks for helping me out.
