### ISSUE TITLE
Epic Online Services Protocol support?

### ISSUE THREAD

**Issue by CosminPerRam** [gamedig/node-gamedig#396]
**What is this feature about?**
Adding support for games that use EOS, as it seems they are more and more frequent nowadays.
I still have to look into this if they at least support some kind of server querying, I made a forum post asking about this [here](Epic Online Services), but at the time of writing, there is no response.

**Additional context/references**
Currently, #395 and #373 are blocked until this is solved.

**Comment by GuilhermeWerner** [comment]
I emailed epic to see if this functionality exists or if they plan to add it.

**Comment by xCausxn** [comment]
https://forums.unrealengine.com/t/eos-server-query-like-the-valve-server-query-protocol/1324417

**Comment by GuilhermeWerner** [comment]
This is what epic responded to my email:

> Hello. From a general standpoint, session information that lives on the Epic Online Services backend can be queried by any client with the appropriate permissions.
> 
> Using the EOS SDK, you're able to communicate with our backend just as any game client would be able to.
> 
> https://dev.epicgames.com/docs/game-services/sessions
> 
> If you require information that is not available on the EOS Session backend, then you'd need to speak with the developers about either having this information added to the online session, or directly communicating with the servers themselves.
> 
> Where you may encounter an obstacle, is that the game developers are responsible for creating and maintaining the client credentials for their own products.
> If you need a set of client credentials that do not require user authentication but still have access to session information, you would need to request a custom set of 'trusted server' client credentials from the developers.

**Comment by Default-01** [comment]
What is the progress on this?

**Comment by GuilhermeWerner** [comment]
I'm studying EOS and doing several tests, when I have something concrete I'll comment here

**Comment by CosminPerRam** [comment]
> What is the progress on this?

Currently none from my side, didnt had too much time to look into it but it seems like they dont provide any server-side query protocols.

> I'm studying EOS and doing several tests, when I have something concrete I'll comment here

Thanks bunch!

**Comment by GuilhermeWerner** [comment]
I sent an email asking battlemetrics how they did it and this was the response:


> Sorry, that's not information we're prepared to disclose. A lot of hard work went into getting a server list for the game and we'd prefer to keep that in-house.
>
> Best Regards,
>
>  BattleMetrics Team

I did several tests with EOS during the week, and according to their documentation and examples, it is possible to obtain this data using the Epic SDK.

Using the EOS SDK and the sample projects they provide, in addition to digging through the ARK Ascended executable, I got the credentials to connect to Epic's services as if my program (in C++) was the game.

The credentials used by the game client (in this case ARK Ascended):
```cpp
struct SampleConstants
{   
    static constexpr char GameName[] = "ARK Survival Ascended";
    static constexpr char ProductId[] = "985dc4d67ff142588b6393c46b1dff84";
    static constexpr char ClientCredentialsId[] = "xyza7891qC5rMxf0e76B4lGe5qePQXNy";
    static constexpr char ClientCredentialsSecret[] = "14BiZqLRckVJ49d9fZ";
    static constexpr char SandboxId[] = "dae80c0d4e3b4d648498b48af609b8bb";
    static constexpr char DeploymentId[] = "ad9a8feffb3b4b2ca315546f038c3ae2";
    static constexpr char EncryptionKey[] = "e624fa4ad499d56822531fe94058cc44a3af014633b83aedfe14346d33c8c35e";
};
```

However, I couldn't find the services, as there are some filters needed for this, and I still couldn't find out which filters are used by the game client.

**Comment by GuilhermeWerner** [comment]
After testing more methods with Ark, with the help of a friend on the gamedig discord, we can create the protocol using EOS.

I was using the EOS SDK in C++, but there is an epic REST API that can be used instead, making implementation much easier.

The point is, to obtain data from a game server via EOS, we need the following credentials:

- client_id
- client_secret
- deployment_id

They vary for each game, and to find them we have to check the game's executables. I already managed to extract those from ASA, so it would be the first to be implemented.

But the base code would be the same, just changing the credentials for each game.

I'll start the implementation and open a PR for the maintainers to evaluate.

**Comment by spenler** [comment]
> After testing more methods with Ark, with the help of a friend on the gamedig discord, we can create the protocol using EOS.
> 
> 
> 
> I was using the EOS SDK in C++, but there is an epic REST API that can be used instead, making implementation much easier.
> 
> 
> 
> The point is, to obtain data from a game server via EOS, we need the following credentials:
> 
> 
> 
> - client_id
> 
> - client_secret
> 
> - deployment_id
> 
> 
> 
> They vary for each game, and to find them we have to check the game's executables. I already managed to extract those from ASA, so it would be the first to be implemented.
> 
> 
> 
> But the base code would be the same, just changing the credentials for each game.
> 
> 
> 
> I'll start the implementation and open a PR for the maintainers to evaluate.

Hey, did this end up getting supported?

**Comment by xCausxn** [comment]
https://github.com/gamedig/node-gamedig/blob/master/protocols/epic.js

That's the current epic implementation.

**Comment by Voroex** [comment]
> I sent an email asking battlemetrics how they did it and this was the response:
> 
> > Sorry, that's not information we're prepared to disclose. A lot of hard work went into getting a server list for the game and we'd prefer to keep that in-house.
> > Best Regards,
> > BattleMetrics Team
> 
> I did several tests with EOS during the week, and according to their documentation and examples, it is possible to obtain this data using the Epic SDK.
> 
> Using the EOS SDK and the sample projects they provide, in addition to digging through the ARK Ascended executable, I got the credentials to connect to Epic's services as if my program (in C++) was the game.
> 
> The credentials used by the game client (in this case ARK Ascended):
> 
> struct SampleConstants
> {   
>     static constexpr char GameName[] = "ARK Survival Ascended";
>     static constexpr char ProductId[] = "985dc4d67ff142588b6393c46b1dff84";
>     static constexpr char ClientCredentialsId[] = "xyza7891qC5rMxf0e76B4lGe5qePQXNy";
>     static constexpr char ClientCredentialsSecret[] = "14BiZqLRckVJ49d9fZ";
>     static constexpr char SandboxId[] = "dae80c0d4e3b4d648498b48af609b8bb";
>     static constexpr char DeploymentId[] = "ad9a8feffb3b4b2ca315546f038c3ae2";
>     static constexpr char EncryptionKey[] = "e624fa4ad499d56822531fe94058cc44a3af014633b83aedfe14346d33c8c35e";
> };
> However, I couldn't find the servers, as there are some filters needed for this, and I still couldn't find out which filters are used by the game client.


How did you manage to find the games specific EOS information? I am looking to get the same information but for Ark Survival Evolved Windows 10 Version of the game, as that does use EOS somewhat, I was looking to see if its possible to do on UWP protected games?

Thanks.
