### ISSUE TITLE
bug: The Front is not supported

### ISSUE THREAD

**Issue by ohmcodes** [gamedig/node-gamedig#401]
I tried to update packages
from nodejs and gamedig itself both project and global
and still receiving invalid game "thefront"

**Comment by xCausxn** [comment]
Hi @ohmcodes 

I have just npm installed the latest github version and thefront is a valid game, so I expect the version you have installed is currently an outdated version from npm.

Global
`npm i -g git+https://github.com/gamedig/node-gamedig`

Project Local
`npm i git+https://github.com/gamedig/node-gamedig`

Both of these will install the latest version from github. However if you want to lock the version you can use the commit hash as well:
`git+https://github.com/gamedig/node-gamedig#f64c4055db2408efeb1cfead67320a0d53580604`

**Comment by CosminPerRam** [comment]
Just as @xCausxn said, a release that includes the front is not here yet, so you'd have to reference this github repository until then.

You can query a The Front server by using the valve protocol with the query port, and thats supported by every version that has the valve protocol implemented.

Closing this as OP hasn't responded and support is added, feel free to reopen if problems or questions arise.
