### ISSUE TITLE
feat: add nova-life

### ISSUE THREAD

**Issue by Yavzkesta** [gamedig/node-gamedig#414]
**What is this feature about?**
pls add this game 

**Additional context/references**
This game uses one game ports 7777
https://steamdb.info/app/1665030/subs/
https://store.steampowered.com/app/885570/NovaLife_Amboise/

**Comment by CosminPerRam** [comment]
Hey, I couldn't find any game server query capabilities. 
I've created a steam discussion thread [here](https://steamcommunity.com/app/885570/discussions/0/4031347532802281316/) and I've emailed the developers.

**Comment by CosminPerRam** [comment]
Hey, they responded via e-mail, here is what they said:
> Good evening,
We have taken your approach into account and we understand its benefits.
Unfortunately, for security and performance reasons, we have suspended all APIs relating to Nova-Life server statistics.
Therefore, our game will unfortunately not be compatible with your platform.
Remaining at your disposal, we wish you a pleasant evening.
Sincerely, [Team Nova banner]

So this will be suspended until they add a way to query server.

**Comment by Maxence1502** [comment]
Hello, they released an update today to use the Steam severs list :
![image](https://github.com/gamedig/node-gamedig/assets/42026318/5f6a5049-5695-4d0a-a9d5-f9e3b9ab959c)

Is it possible to make it compatible with this ?

**Comment by CosminPerRam** [comment]
Yes!
I have found this server: `88.198.48.91:27015` which reports Nova-Life: Amboise and the appropiate game app id.

**Comment by CosminPerRam** [comment]
@Maxence1502 could you attempt using the linked PR? (or just with any valve-protocol game (like `teamfortress2`)).

**Comment by Maxence1502** [comment]
I confirm that it's working, you can merge :)
