### ISSUE TITLE
feat: Rising world has a query offset by -1

### ISSUE THREAD

**Issue by dgibbs64** [gamedig/node-gamedig#437]
Rising world query port is offset by -1

Game         4255  udp   
Query        4254  tcp
RCON         4253  tcp

**Comment by CosminPerRam** [comment]
Seems like Rising World has two server types, 'Java' and the newer one 'Unity'.
In the [Java](https://forum.rising-world.net/thread/8075-dedicated-server-setup-java-version/) and [Unity](https://forum.rising-world.net/thread/11490-dedicated-server-setup-new-version/) dedicated server guides both list `4255` as being the default server with the -1 offset for queries, thanks for pointing this out.
