### ISSUE TITLE
feat: V-rising has an ofset of either 1 or 15

### ISSUE THREAD

**Issue by dgibbs64** [gamedig/node-gamedig#438]
**What is this feature about?**
Doing a bit of research on port offset and found that V-rising servers tend to either have an offset of 1 or 15 depending upon the server provider. I am assuming that the developer's default is 15 but some providers choose to do a +1 for simplicity. So it might be a good idea to add a feature for multiple offsets.

**Additional context/references**
I am noticing this is a trend for many game servers with separate query ports so I believe allowing to query multiple common ports will increase the success rate. Maybe a default of checking the default port of set first then trying +1

**Comment by CosminPerRam** [comment]
Following their [official server setup guide](https://github.com/StunlockStudios/vrising-dedicated-server-instructions) tells that the query port by default is +1 than the game port:
![image](https://github.com/gamedig/node-gamedig/assets/7972857/19d99a77-7342-487b-82df-2d4dd1e87d0d)

Have you found other guides or came across many servers with +15 offset?

**Comment by podrivo** [comment]
I haven't found any docs about this either, but there's definitely a pattern on servers if you check this list: https://www.battlemetrics.com/servers/vrising

+1 and +15 on almost all servers.

**Comment by CosminPerRam** [comment]
Oh, looks like it, alright.

**Comment by podrivo** [comment]
Completed by https://github.com/gamedig/node-gamedig/pull/471 and https://github.com/gamedig/node-gamedig/pull/483.
It's ok to close! (:
