### ISSUE TITLE
Support Satisfactory game

### ISSUE THREAD

**Issue by Maxence1502** [gamedig/node-gamedig#442]
Hello,

Is it possible to support this game : https://store.steampowered.com/app/526870/Satisfactory/

Thank you :)

**Comment by CosminPerRam** [comment]
Hello, please use the issue templates.
It seems that Satisfactory doesn't support valve server queries, but I've found a mod thats made for this: [FicsIt Remote Monitoring](https://ficsit.app/mod/FicsitRemoteMonitoring).
I've seen on the [steamdb page of the dedicated server](https://steamdb.info/app/1690800/) that it uses Epic Online Services, it could be queried that way, but finding the necessary keys for the epic protocol is tricky  here.

**Comment by CosminPerRam** [comment]
None that I know of at least unfortunately :/

**Comment by CosminPerRam** [comment]
From their [patchnotes](https://www.reddit.com/r/SatisfactoryGame/comments/1fdjz13/patch_notes_satisfactory_10_build_365306/):
> We have added support for an HTTP API, so it is now possible to create applications to communicate with the dedicated server for those who are interested in developing tools for it :) 

And upon starting a dedicated server (hope it means what I think):
> PacketHandlerLog: Loaded PacketHandler component: FactoryDedicatedServer.DSQueryHandlerComponentFactory (DSQueryHandlerComponent)

So I guess its possible, I'll look into it later on.

**Comment by CosminPerRam** [comment]
From their Discord server:
![image](https://github.com/user-attachments/assets/941d6bc7-bcfe-483f-a335-dd274ed40f63)

I unfortunately do not own the game.

**Comment by Destarianon** [comment]
[DedicatedServerAPIDocs.md](https://github.com/user-attachments/files/16957580/DedicatedServerAPIDocs.md)
Here is a reference to the API documentation.

**Comment by Maxence1502** [comment]
Let me know if you need help for testing or debugging in game

**Comment by Smidy13** [comment]
Investigated this and will look at contributing. There are two requests needed, one to get a authentication token and then the second to get the server state. Making some notes here and will continue tomorrow.

**First Request to Get Authorization Token**
```
> POST https://localhost:7777/api/v1
> Content-Type: application/json
> data {"function":"PasswordlessLogin","data":{"MinimumPrivilegeLevel":"Client"}}
```

This will return a JSON with an authenticationToken.

**Second Request to Get Server State**
```
POST https://localhost:7777/api/v1
> Content-Type: application/json
> Authorization: Bearer **authenticationToken**
> data {"function":"QueryServerState","data":{"clientCustomData":{}}}
```

This will return a JSON with serverState including activeSessionName, numConnectedPlayers, playerLimit, techTier, activeSchematic, gamePhase, isGameRunning, totalGameDuration, isGamePaused, averageTickRate and autoLoadSessionName.

**Comment by xCausxn** [comment]
Looking forward to seeing the PR and getting another contributor to GameDig 👍
