### ISSUE TITLE
feat: option to make requestRules mandatory

### ISSUE THREAD

**Issue by podrivo** [gamedig/node-gamedig#455]
**What is this feature about?**
I was wondering if adding an option to make `--requestRules` mandatory would be a good idea.

**Additional context/references**
I understand that it needs to be optional by default, as not all Valve servers have rules enabled, but in my case the rules object is really important and it's not currently working together with `--maxAttempts`. If only the rules query is not responded, it will not fire a second time to get the full packet from the server.

By making an option to make it mandatory, I guarantee that `--maxAttempts` will always grab the rules object for my query.

Let me know if this makes sense and I can start working on a solution for us! 😄

**Comment by CosminPerRam** [comment]
I have thought of this before, to be able (for the protocols that do more than 1 request (valve for example)) to make only a specific request.
Could definitely be a feature!

**Comment by CosminPerRam** [comment]
Completed by #458.
