### ISSUE TITLE
Error: UDP - Timed out

### ISSUE THREAD

**Issue by axelcypher** [gamedig/node-gamedig#457]
**Describe the bug**
I can't get my server's Info. heres the Repo: https://github.com/axelcypher/discord_gmod_bot It's a fork of another bot I wanted to modify, so that the bot displays the player cont in his status. The Server is a dockerized Garry's Mod server, running in host mode. My bot also runs as a docker container on the same machine. 

```
Error: Failed all 1 attempts
    at QueryRunner.run (/app/node_modules/gamedig/lib/QueryRunner.js:96:21)
    at async Gamedig.query (/app/node_modules/gamedig/lib/index.js:11:16)
    at async Gamedig.query (/app/node_modules/gamedig/lib/index.js:19:16)
Attempt #1 - Port=27016 Retry=0:
Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (/app/node_modules/gamedig/lib/Promises.js:7:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

```

Here's the Code responsible for fetching the server Info:

```
bot.on('ready', () => {
  
...
  	
  setInterval(() => {
		gamedig.query({
        		type: 'garrysmod',
              		host: GAMESERVER_HOST,
              		port: GAMESERVER_QUERY_PORT,
			requestRules: true
		}).then((state) => {							 
			bot.user.setActivity(`${state.players.length}/${state.maxplayers} online!`);
              		console.log(`${state.players.length}/${state.maxplayers} online!`);
        	}).catch((error) => {
        		bot.user.setActivity(`Currently offline!`);
              		console.error(error);
          	});
  }, 10000); 
	
  //bot.setInterval(activityupdate(),3000);


});
```

GAMESERVER_HOST and GAMESERVER_QUERY_PORT are provided through environment variables.
As the both servers running locally, the GAMESERVER_HOST is the local IP of my docker host.
The Port is 27016, as due to some strage firewall behaviour  people from the outside couldn't connect on port 27015.

Dependencies are:

```
    "chalk": "^4.1.1",
    "discord.js": "^14.14.1",
    "dotenv-flow": "^3.2.0",
    "http": "0.0.1-security",
    "https": "^1.0.0",
    "gamedig": "^4.3.1"
```
It's running on Node 18.

Anyone an idea what iv'e missed here?

**Comment by axelcypher** [comment]
Yah, nevermind. 
I've never tried to run the bot in host mode. A couple of issues below me were the solution to this problem. Now its working <.<

Hope this helps anyone who is as dumb as me

**Comment by CosminPerRam** [comment]
Happens from time to time to everyone (:
Best of luck!
