### ISSUE TITLE
Address option not documented

### ISSUE THREAD

**Issue by Douile** [gamedig/node-gamedig#462]
There is an option to skip DNS resolution by using the address option but this is not documented in the README or in the typescript types (note this can be used in conjunction with the host option to set the hostname but provide your own IP).

**Comment by podrivo** [comment]
Do you mind pointing me to an example and/or existing notes about this?
I'll make sure to add this documentation in our README. (:

**Comment by Douile** [comment]
After a bit of digging it looks like the option was added here: https://github.com/gamedig/node-gamedig/commit/0d1577fa35035a148769b0230011aefad870f770

Currently: https://github.com/gamedig/node-gamedig/blob/c81037040b9c6ad1bfd716def88010a5ddee5393/protocols/core.js#L71-L80

If address is set then DNS resolution is skipped (both SRV and A/AAAA). Which makes it seem like it should only accept IP addresses however it is passed to [node:net.connect](https://nodejs.org/docs/latest/api/net.html#netconnectport-host-connectlistener) which itself will do an implicit getaddrinfo call (DNS lookup).

If address isn't set then host is looked up and put in options.address.

Important to note here is that host is used elsewhere other than address lookup, for example minecraft java uses it as part of the query:
https://github.com/gamedig/node-gamedig/blob/c81037040b9c6ad1bfd716def88010a5ddee5393/protocols/minecraftvanilla.js#L9

(I believe in this case we would error if host is not set, that should possibly be changed).

However its usage is inconsistent: HTTP calls will not set the `Host` header to the host option, they use the address (which should also possibly be changed).

---

An example from: https://github.com/discord-gamestatus/discord-gamestatus

```javascript
const address = await resolveAddress(hostname);

if (shouldBlock(address)) {
    throw new AddressBlockedError(
      `Resolved address (${address.host} -> ${address.ip}) is blocked`
    );
}

gamedig.query({
      type: queryType,
      host: address.host,
      address: address.ip,
      ipFamily: address.family === "ipv6" ? 6 : 4,
      port: address.port,
});
```

Related but not relevant: It's important that the IP address is passed directly to gamedig here as DNS can be made to be inconsistent: if the hostname is resolved twice an attacker could bypass the blocklist.

**Comment by podrivo** [comment]
Thank you for the context and example! 🙌 

I haven't found any documentation in the commit history about it. Wondering why this wasn't included... Regardless, there's a PR (https://github.com/gamedig/node-gamedig/pull/461) with README updates, that's a good candidate to include it. 

What do you think it could be a good description for `address`, considering what you've mentioned? 
What is the default value?

**Comment by Douile** [comment]
It defaults to undefined (not set), if its not set its overwritten during the query.

I would probably say something like:

```js
/**
 * @param {string | undefined} options.address Override the IP address of the server skipping DNS resolution. When set host will not be resolved instead address will be connected to, however some protocols still use host for other reasons e.g. as part of the query.
 */
```

**Comment by podrivo** [comment]
Thank you so much @Douile! ✨
