### ISSUE TITLE
feat: Stabilize `version` field

### ISSUE THREAD

**Issue by dgibbs64** [gamedig/node-gamedig#468]
**What is this feature about?**
Currently, there are many ways to get the version of a game server 
e.g the ones I found are
```
gamedig.raw.gamespy.raw.version # gamespy
gamedig.raw.vanilla.raw.version # minecraft java
gamedig.raw.bedrock.raw.version # minecraft bedrock
gamedig.raw.gamever
gamedig.raw.shortversion
gamedig.raw.si_version
gamedig.raw.gameversion
gamedig.raw.version
gamedig.raw.attributes.BUILDID_s.gamedig.raw.attributes.MINORBUILDID_s //ARK:SA
gamedig.raw.attributes.VERSION_S //Palworld

```
In a similar vein to name, map, maxplayers please could a top-level version object be created.

**Comment by podrivo** [comment]
That's interesting! I can take a deeper look at how this work across games.

**Comment by Douile** [comment]
Version is definitely one of the common ones. We have a table of all the response variables we support in rust that might be helpful: https://github.com/gamedig/rust-gamedig/blob/main/RESPONSES.md .

**Comment by podrivo** [comment]
I've started investigating this, and found that some games have the version already included, so it's just a simple task of reassigning keys in the state object.

But some games don't have the version already parsed, and it will need extra effort to be parsed, or it might not even exist in the response. If that's the case, should we consider `version` a top level key or not?

**Comment by Douile** [comment]
> But some games don't have the version already parsed, and it will need extra effort to be parsed, or it might not even exist in the response. If that's the case, should we consider version a top level key or not?

I would say this is fine just define the version top-level type as undefined or string for example (or set to null when it doesn't exist).

To this end I'm not sure if all the responses here have the same type, this is fine javascript wise but it might be nicer to convert them all to a single type so users know exactly what will be on the top-level response object. (I'm not sure though giving them the exact type is also better in some cases).

> So game_version for example, is not always present in specific protocols?

Yep, from the protocols that the rust version supports gamespy2, minecraft bedrock, unreal2, and savage2 don't have a game_version value.

**Comment by podrivo** [comment]
Nice! Thank you for the explanation! (:

**Comment by dgibbs64** [comment]
Just added yet another version for palworld `gamedig.raw.attributes.VERSION_S` 😄

**Comment by podrivo** [comment]
@dgibbs64 Apart from ARK:SA and Palworld, do you know which protocols are these examples?

**Comment by dgibbs64** [comment]
I just added a few from memory btu cant remember the others

**Comment by CosminPerRam** [comment]
Hey, feel free to make another issue if you encounter any problems with the new field (:
Kudos to @podrivo!
