### ISSUE TITLE
Change retry logic to "breadth first"

### ISSUE THREAD

**Issue by Douile** [gamedig/node-gamedig#479]
**What is this feature about?**
Currently we handle retries by queuing up a list of possible query settings then iterating this list and trying each one for the amount of retries attempts before moving on to the next set of possible settings.

This looks like this (max retries 2 with 3 different settings):
```
Attempt 1: settings=0 retries=0
Attempt 2: settings=0 retries=1
Attempt 3: settings=1 retries=0
Attempt 4: settings=1 retries=1
Attempt 5: settings=2 retries=0
Attempt 6: settings=2 retries=1
```

Depending on the situation (how good first guess is) it might be better to move on to the next possible query settings after the previous fails. This would look something like this:

```
Attempt 1: settings=0 retries=0
Attempt 2: settings=1 retries=0
Attempt 3: settings=2 retries=0
Attempt 4: settings=0 retries=1
Attempt 5: settings=1 retries=1
Attempt 6: settings=2 retries=1
```

By iterating this way we explore the possible ports the server could be on quicker (when maxRetries is > 1) so in theory we would return a result faster when the correct port is not the first in the list.

This would be slower in the case that there is a timeout querying the first guess but the first guess is the correct port.

**Additional context/references**
https://github.com/gamedig/node-gamedig/blob/b481425dbf1d50dcb3e756897d7cc15a46cc04c9/lib/QueryRunner.js#L65-L88

**Comment by CosminPerRam** [comment]
Linked a PR, hope that's what you wanted (:

**Comment by Douile** [comment]
Looks good. Thanks.
