### ISSUE TITLE
feat: Support Palworld game

### ISSUE THREAD

**Issue by Maxence1502** [gamedig/node-gamedig#491]
**What is this feature about?**

Hello,

Is it possible to support this game : https://store.steampowered.com/app/1623730/Palworld/

Thank you :)

**Comment by CosminPerRam** [comment]
I couldn't find any info at all regarding direct server queries.
Seems that the game is available through the steam servers browser:
![image](https://github.com/gamedig/node-gamedig/assets/7972857/7d1d1c83-e980-4631-9feb-49d0744ff87d)
(screenshot courtesy of @jammsen)
And its seems the game has the port `27015` opened (which usually indicates a valve protocol, but it doesnt respond on it): 
![image](https://github.com/gamedig/node-gamedig/assets/7972857/5a1295e4-2edf-4a29-b128-ebf2a697eb1c)

**Comment by jonathanprl** [comment]
It's using EOS and works similar to the game `asa`, although requires extra EOS authentication steps. I've got something working although it's not querying every Palworld server, but does query some...

https://github.com/jonathanprl/node-gamedig/commit/514101ff81a80b6f1ffc85b80ccbd8d9ce055602

**Comment by CosminPerRam** [comment]
Forgot to mention that the game's engine is unreal so it probably runs EOS.

Well, a partial solution is better than no solutions.
> although requires extra EOS authentication steps

Hmm, that could go the same about some other EOS games (cc as I know you've looked into other games: @GuilhermeWerner).

> https://github.com/jonathanprl/node-gamedig/commit/514101ff81a80b6f1ffc85b80ccbd8d9ce055602

Feel free to make a PR whenever you think it's meargeable (:

**Comment by jammsen** [comment]
Maybe that helps out a little
https://tech.palworldgame.com/community-server-guide

**Comment by jammsen** [comment]
Feel free to use my server as test-server too:
https://www.battlemetrics.com/servers/palworld/25160493

**Comment by GuilhermeWerner** [comment]
> Forgot to mention that the game's engine is unreal so it most probably runs EOS.
> 
> Well, a partial solution is better than no solutions.
> 
> > although requires extra EOS authentication steps
> 
> Hmm, that could go the same about some other EOS games (cc as I know you've looked into other games: @GuilhermeWerner).
> 
> > [jonathanprl@514101f](https://github.com/jonathanprl/node-gamedig/commit/514101ff81a80b6f1ffc85b80ccbd8d9ce055602)
> 
> Feel free to make a PR whenever you think it's meargeable (:

From what I discovered by studying the Epic API, and implementing the protocol for ASA.

In some games a user account is required to access EOS, in the case of ASA this also occurred to me, using the game client credentials, it was not possible, however with the dedicated server credentials it was possible, as the dedicated server does not need a user account to access the API.

This may vary from game to game, and although the credentials are from the dedicated server, I extract them from the game client, and not from the server executable itself.

Here is an image of the different ASA credentials, as an example:
![image](https://github.com/gamedig/node-gamedig/assets/26710260/a532d7fd-a004-4dba-9e1f-6d48c4dc8c6f)

**Comment by Maxence1502** [comment]
Hello,

The solution that was merge seems partially functional, sometimes it works, sometimes it doesn't.
Shouldn't this issue be left open until a real solution can be found?

**Comment by Maxence1502** [comment]
Even when the query returns a result, the number of players is incorrect:
![image](https://github.com/gamedig/node-gamedig/assets/42026318/b9338ae3-b81d-41d7-b05a-d9a058089698)

**Comment by jammsen** [comment]
@CosminPerRam *Ping* - Open question remains.

**Comment by Maxence1502** [comment]
Done : https://github.com/gamedig/node-gamedig/issues/507

**Comment by jammsen** [comment]
Added the PR #508 after changing this and testing it
