### ISSUE TITLE
feat: Updated typescript types for v5 release

### ISSUE THREAD

**Issue by a-sync** [gamedig/node-gamedig#502]
I created a PR draft at DefinitelyTyped for the current #master branch (future v5): https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68279  

Any suggestion/contribution is welcome, i only submitted this issue to create awareness that this exists. (I hope thats ok.)

Once v5.x.x is released on npmjs the eslint rule: `"@definitelytyped/npm-naming": "off"` can be removed and the PR merged if no new feature or change is added to gamedig.

**Comment by CosminPerRam** [comment]
Hey, thanks bunch for this.
#496 will require some changes when merged (soon).

**Comment by a-sync** [comment]
> #496 will require some changes when merged (soon).
Noted.

@CosminPerRam noticed an irregular/undocumented prop: games[].options.**query_port**
Is that a typo in games.js by any chance? Only used at 3 games and seems like its an offset in two cases and a port number in one.  🤔

**Comment by a-sync** [comment]
DT merged/released it so i guess so. Other changes can go to DT directly.  

On a different note: for beta releases in the npmjs registry it would be better to use the `beta `tag, anf leave the `latest `tag for the stable release.
