### ISSUE TITLE
Add Enshrouded

### ISSUE THREAD

**Issue by CptC0nfus3d** [gamedig/node-gamedig#505]
Pleace add Palworld and Enshrouded

**Comment by CosminPerRam** [comment]
Hello, please use the issue template.
Palworld support is already added by #495 and available in GameDig `5.0.0-beta.0`.
I'll rename this issue to the `Enshrouded` game only.

**Comment by podrivo** [comment]
Enshrouded seems to not have been released yet.

@CptC0nfus3d Do you have an IP:PORT example of a Enshrouded server? Thank you!

**Comment by Maxence1502** [comment]
Hello, the game and servers are live :)

**Comment by GuilhermeWerner** [comment]
I'm implementing it, I'll open a PR
