### ISSUE TITLE
bug: Incorrect numplayers on Palworld

### ISSUE THREAD

**Issue by Maxence1502** [gamedig/node-gamedig#507]
**Describe the bug**
The number of players returned is 0 even though there are several on the server.

**Steps To Reproduce**
Query any Palworld server.

**Expected behaviour**
Should the "PLAYER_L" be returned?

![image](https://github.com/gamedig/node-gamedig/assets/42026318/59265792-d026-4246-a483-67a8b0eeec7d)

**Comment by jammsen** [comment]
Added the PR #508 after changing this and testing it

**Comment by CosminPerRam** [comment]
Closed by #508.
