### ISSUE TITLE
Support for ETS2

### ISSUE THREAD

**Issue by Araxion** [gamedig/node-gamedig#513]
Hey,
Is it possible to support ETS2? https://store.steampowered.com/app/227300/Euro_Truck_Simulator_2/
Thanks! :)

**Comment by GuilhermeWerner** [comment]
Hello, would you have an IP of a server for us to test? I tried to create one but I don't have the game.

**Comment by Araxion** [comment]
Hey, thanks, you can use this server 77.78.90.150:20600

Dne ne 28. 1. 2024 19:01 uživatel Guilherme Werner ***@***.***>
napsal:

**Comment by podrivo** [comment]
Tried running `tools/attempt_protocols.js` on `77.78.90.150:20600` and `77.78.90.150`, but it didn't work on any protocol.

**Comment by podrivo** [comment]
It seems ETS2 works with Valve protocol. 
Got some servers to test on this list: https://gamemonitoring.net/euro-truck-simulator-2/servers

Tried running with valve protocol and it works:

```
gamedig --type protocol-valve 89.163.193.8:27016 --pretty

{
  "name": "!! Zockerbude -1- (German only 24/7)",
  "map": "/map/europe.mbd",
  "password": false,
  "raw": {
    "protocol": 17,
    "folder": "xjeEAd/V2y8=",
    "game": "Euro Truck Simulator 2",
    "appId": 227300,
    "numbots": 6,
    "listentype": "l",
    "environment": "l",
    "secure": 0,
    "version": "1.0.0.0",
    "steamid": "90180017515203591",
    "tags": [
      "ZABlAEsCAAA="
    ],
    "players": [
      {
        "name": "",
        "score": 0,
        "time": 2093.457763671875
      },
      {...}
    ]
  },
  "maxplayers": 8,
  "numplayers": 6,
  "players": [],
  "bots": [
    {
      "name": "",
      "raw": {
        "score": 0,
        "time": 2093.457763671875
      }
    },
    {...}
  ],
  "queryPort": 27016,
  "connect": "89.163.193.8:27015",
  "ping": 239
}
```
