### ISSUE TITLE
bug: palworld server find only with external ip and wrong port

### ISSUE THREAD

**Issue by nodiaque** [gamedig/node-gamedig#515]
**Describe the bug**
When querying palworld, you must provide external ip to find (it doesn't scan local). Also, it default to scan port 8221 but port is 8211

**Steps To Reproduce**
gamedig --type palworld localip:8211 and it won't work.
Can try with dns too and won't work, must user real ip.

using real ip with port 8221 (Default in config file) won't work

**Expected behavior**
Use loal ip or dns to scan local network and check if online.
If using dns, at worst find the ip from that dns and use it

**Comment by GuilhermeWerner** [comment]
Hello, the incorrect port is really a bug.

On the other hand, the fact that it only works with external IP is because it uses EOS (Epic Online Services), which only works with external IP, all games that use it (ARK: Survival Ascended and The Isle Evrima) do not respond to the local address.

**Comment by jammsen** [comment]
There you go -> #516

**Comment by CosminPerRam** [comment]
Closing this as #516 has been merged, feel free to reopen if anythings comes by.
