### ISSUE TITLE
bug: Palworld player array empty

### ISSUE THREAD

**Issue by DaliborTrampota** [gamedig/node-gamedig#520]
**Describe the bug**
response.players is empty array even though players are joined

**Screenshots or Data**
![image](https://github.com/gamedig/node-gamedig/assets/31895316/c711c9f2-915f-4ad4-b9b7-534e2684d0e7)

**Additional context**
Im on master due to the beta.0 not showing numplayers 0 even when there are players joined
"gamedig": "github:gamedig/node-gamedig"

**Comment by podrivo** [comment]
Hello @DaliborTrampota. This has been fixed, but not yet published.
Currently, you can grab players from `state.raw.attributes.PLAYERS_`

Related https://github.com/gamedig/node-gamedig/issues/507 and https://github.com/gamedig/node-gamedig/pull/508

**Comment by Maxence1502** [comment]
I think he wants to get the player names instead of the number

**Comment by podrivo** [comment]
Palworld's protocol (EOS) does not provide players data.
