### ISSUE TITLE
bug: enshrouded is on the supported game list but returning invalid game response.

### ISSUE THREAD

**Issue by Cabecinha84** [gamedig/node-gamedig#524]
I am with latest gamedig version, v5.0.0.beta2 and I am getting "Invalid game: enshrouded" when testing a server.
The game is on the gamelist.
To test execute -> gamedig --type enshrouded serverip:15636

**Comment by podrivo** [comment]
Hey @Cabecinha84!

If you're using `v5.0.0.beta2` you should not see `"Invalid game: enshrouded"`.
It's working as expected on my end.

Make sure you have the latest version by running `npm install -g gamedig`

—

```
gamedig --type enshrouded 144.126.152.119:29515 --pretty

{
  "name": "Enshrouded (US East) Public Server #1",
  "map": "",
  "password": false,
  "raw": {
    "protocol": 17,
    "folder": "Enshrouded",
    "game": "Enshrouded",
    "appId": 1203620,
    "numbots": 0,
    "listentype": "d",
    "environment": "w",
    "secure": 0,
    "version": "0.0.15.0",
    "steamid": "90179935383504905",
    "tags": [
      "6;487046xx(\u0002"
    ],
    "players": []
  },
  "maxplayers": 16,
  "numplayers": 0,
  "players": [],
  "bots": [],
  "queryPort": 29515,
  "connect": "144.126.152.119:29500",
  "ping": 194
}
```

**Comment by Cabecinha84** [comment]
> npm install -g gamedig

was missing this "npm install -g gamedig"
despite on the project the npm was updated when executing it was using the global install that wasn't updated. Thank you!

**Comment by podrivo** [comment]
Glad you got it working! (:
