### ISSUE TITLE
bug: Terraria protocol doesn't seem to be working

### ISSUE THREAD

**Issue by Konrad13x** [gamedig/node-gamedig#529]
**Describe the bug**
The terraria protocol used to query terraria servers seems to be not working.

**Steps To Reproduce**
I used gamedig on uptime kuma to ping one of my terraria game servers. The IP is my domain that is used to join the server with the port being the default 7777 terraria. I used the terraria:tshock protocol. Contributor podrivo also reports the issue with protocol citing that the protocol didn't work on other confirmed servers.

**Expected behavior**
The query of the terraria server to work.

**Comment by podrivo** [comment]
I've tried several servers in this [server list](https://terraria-servers.com/), but none responded.
But then I took a look at the documentation and found this:

https://github.com/gamedig/node-gamedig/blob/ce9a1b0fecfb29bd2f6d5a7c6e9e7eba06ba2b09/GAMES_LIST.md?plain=1#L443-L447

Are you using the server mod and passing the token when querying?

**Comment by podrivo** [comment]
Hey @Konrad13x!

Did you manage to fix the issue by passing the token and using the server mod?
Just wondering if we should take a look at the protocol or if it's working.

Thank you!
