### ISSUE TITLE
Myth of Empires support

### ISSUE THREAD

**Issue by scarecr0w12** [gamedig/node-gamedig#542]
Please add in myth of empires support,
https://store.steampowered.com/app/1371580/Myth_of_Empires/

Re-Release is on the 21st of Feb this year.

**Comment by podrivo** [comment]
Tried servers from this list: https://www.battlemetrics.com/servers/moe
But it didn't work on any protocol we have today.

**Comment by scarecr0w12** [comment]
> Tried servers from this list: https://www.battlemetrics.com/servers/moe But it didn't work on any protocol we have today.

Yeah, from my understanding, it may be similar to how the Front is/was where it has to be pulled from a master list.

**Comment by denizkoekden** [comment]
Yes it seems as if they are not 100% Compatible with the protocol specs. I have a few methods to debug this:
- Custom PHP Script I wrote a few years ago -> Can not handle this game but can handle The Front and any other game like CS, Enshroueded, etc.
- Source Admin Tool -> Can Handle the Game and show info about it
- HLSW -> also kinda handles the game and shows info about it

So maybe it needs some workaround to get this game working with HL2 Query.

**Comment by CosminPerRam** [comment]
Hey, linked the implementation PR, could someone double check? (:
