### ISSUE TITLE
Palworld only listed if using default game port

### ISSUE THREAD

**Issue by ionutshiro** [gamedig/node-gamedig#554]
I've tried adding couple of servers but they only work with the default game port 8211 which shouldn't be the case as the gameport can be any other as long as it's listed in game server browser and other trackers.
Any ideea or am i doing something wrong?

**Comment by treemlt** [comment]
![palworld not working](https://github.com/gamedig/node-gamedig/assets/153841591/13e10e5e-7ddc-4e17-8a21-9493ac6da2f4)

This is after the palworld update

**Comment by ionutshiro** [comment]
> ![palworld not working](https://private-user-images.githubusercontent.com/153841591/308289110-13e10e5e-7ddc-4e17-8a21-9493ac6da2f4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTgxMDksIm5iZiI6MTcwOTA1NzgwOSwicGF0aCI6Ii8xNTM4NDE1OTEvMzA4Mjg5MTEwLTEzZTEwZTVlLTdkZGMtNGUxNy04YTIxLTk0OTNhYzZkYTJmNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxODE2NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOWFiYTQwMTIyZTkyNjE5NWFlNDQ5OWFhMzM5YWNjY2Y1MjhhNmI1NWU5NWI3ZDdjN2I2NjIyMjg4NmZiYzJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G2jZvowB6AL_N-NeCc90c1ewSaBcLQUmUwV12pjyHoQ)
> 
> This is after the palworld update

Did you restart to update the Palworld server?

**Comment by treemlt** [comment]
yes. I opened a diferent issue for this

**Comment by podrivo** [comment]
Possible duplicate https://github.com/gamedig/node-gamedig/issues/555

**Comment by CosminPerRam** [comment]
Closing this as its superseeded by #555.

**Comment by ionutshiro** [comment]
> Closing this as its superseeded by #555.

My inquiry is completly different from #555 , i'm mentioning that before the update it did not working unless we use the default 8211 port which is not the case

**Comment by CosminPerRam** [comment]
Oh, sorry for the missunderstanding then.

**Comment by ionutshiro** [comment]
> Oh, sorry for the missunderstanding then.

All good , but yeah as mentioned in my original post query is  not locked for 8211 by the game  normally but gamedig locks it to 8211 i guess?

**Comment by CosminPerRam** [comment]
This'll be hard to debug as the update just rolled out and it seems the query responds with no servers at all.

> but gamedig locks it to 8211 i guess?

It does not, gamedig uses your provided port:
https://github.com/gamedig/node-gamedig/blob/b0af081d36eb87938665c8a22045797b49ffd195/protocols/epic.js#L119-L121

**Comment by ionutshiro** [comment]
Well provider port does not work unless 8211 no matter the port even opened un firewall

Sent from Yahoo Mail on Android 
 
  On Thu, 29 Feb 2024 at 0:11, ***@***.***> wrote:   


This'll be hard to debug as the update just rolled out and it seems the query responds with no servers at all.


but gamedig locks it to 8211 i guess?


It does not, gamedig uses your provided port:
https://github.com/gamedig/node-gamedig/blob/b0af081d36eb87938665c8a22045797b49ffd195/protocols/epic.js#L119-L121

**Comment by ionutshiro** [comment]
Not sure as palworld server browser lists it regardless if 8211 or not

Sent from Yahoo Mail on Android 
 
  On Thu, 29 Feb 2024 at 0:15, ***@***.***> wrote:   


I cannot say for sure, but I think EOS lists your server only if it uses the default port (8211) (could be the case just for Palworld).

**Comment by CosminPerRam** [comment]
> Not sure as palworld server browser lists it regardless if 8211 or not

Many if not all games do have their own 'closed' services for handling this kind of stuff.

**Comment by CosminPerRam** [comment]
In #555 I've noted that Palworld seems to moved to a proprietary master server, api endpoint [here](https://api.palworldgame.com/server/list) and it seems that server's port is included there and server that aren't using the default port are listed there.

Again as I've said, Palworld 0.1.5 made changes to the EOS and we cannot really look into this issue or solve it as we can't properly query new servers with the 'old' protocol, so I think this could be closed.

**Comment by ionutshiro** [comment]
> In #555 I've noted that Palworld seems to moved to a proprietary master server, api endpoint [here](https://api.palworldgame.com/server/list) and it seems that server's port is included there and server that aren't using the default port are listed there.
> 
> Again as I've said, Palworld 0.1.5 made changes to the EOS and we cannot really look into this issue or solve it as we can't properly query new servers with the 'old' protocol, so I think this could be closed.

Can we still query Palworld using gamedig at all or not ?

**Comment by GuilhermeWerner** [comment]
> In #555 I've noted that Palworld seems to moved to a proprietary master server, api endpoint [here](https://api.palworldgame.com/server/list) and it seems that server's port is included there and server that aren't using the default port are listed there.

I couldn't find any documentation about this API, the official page has nothing in English or Japanese.

https://tech.palworldgame.com/category/api
https://tech.palworldgame.com/ja/category/api

However, according to my tests, it is an API with pagination and it is also possible to filter by name or region, although I don't know if this filtering by region is working correctly.

![image](https://github.com/gamedig/node-gamedig/assets/26710260/4895b8a0-8e3d-40fc-8b12-eb9536964e4a)

**Comment by CosminPerRam** [comment]
Thanks for the extra info, I will make an initial implementation and will link #555 in it.

> Can we still query Palworld using gamedig at all or not ?

As of this message no, but as we just found another method of doing so, supposedly shortly yes.

> so I think this could be closed.

Closing this, feel free to reopen if something is not clear.
