### ISSUE TITLE
Palworld broken after update

### ISSUE THREAD

**Issue by treemlt** [gamedig/node-gamedig#555]
![palworld not working](https://github.com/gamedig/node-gamedig/assets/153841591/9061cfb9-6ef8-412f-82ac-6732dc9646e4)

After the new palworld update it seems to have broken the way the data is retrieved.

**Comment by indifferentbroccoli** [comment]
Also facing this problem

**Comment by dgibbs64** [comment]
Can confirm Palworld update has broken querying 😐

**Comment by podrivo** [comment]
Palworld uses Epic Online Services to query servers and it needs some credentials to make it work.
Maybe these credentials have changed?

We currently have these ones:

https://github.com/gamedig/node-gamedig/blob/b0af081d36eb87938665c8a22045797b49ffd195/protocols/palworld.js#L7-L10

**Comment by CosminPerRam** [comment]
Very possible, although it'll be better to move to RCON for this.

**Comment by jammsen** [comment]
> Very possible, although it'll be better to move to RCON for this.

@CosminPerRam - According to the DefaultPalWorldSettings.ini the key-value pair `RCONEnabled=false` is standard set to false.

Even if enabled, the values you can get from RCON are much more limited then what you got from the EOS service, see: https://tech.palworldgame.com/settings-and-operation/commands

**Comment by jammsen** [comment]
> `/Info` and `/ShowPlayers` should be all we need (although I don't exactly know what fields they provide.

There you go:
```shell
$:~/development/docker-palworld-dedicated-server$ docker exec palworld-dedicated-server rcon info
Welcome to Pal Server[v0.1.5.1] jammsen.test.local
$:~/development/docker-palworld-dedicated-server$ docker exec palworld-dedicated-server rcon showplayers
name,playeruid,steamid
j,a,m,m,s  e,n,!123,130XXXXXXXX,765XXXXXXXXXXXXXXX
```

And yes my charactername is "j,a,m,m,s  e,n,!123" on purpose for my "player-detection" rcon tool. Normally there should be only like "jammsen".

> RCON has been discussed to be a feature that will come eventually, but It'll take a little while until then.

Do you mean as a native feature to lookup data instead of queries to master-servers-alike systems?

**Comment by dkoz** [comment]
I've been able to successfully query my server by name instead of IP address just by adjusting the filter.

**Comment by ionutshiro** [comment]
> I've been able to successfully query my server by name instead of IP address just by adjusting the filter.

Well what if you decide to change name at some point ? You have to re-add it ?

**Comment by dkoz** [comment]
> > I've been able to successfully query my server by name instead of IP address just by adjusting the filter.
> 
> Well what if you decide to change name at some point ? You have to re-add it ?

Probably. I'm targeting it based on `attributes.NAME_s` and it's one word sensitive for some reason. It's really annoying to work with.

**Comment by ionutshiro** [comment]
Do we have any updates on this other than using name to query?

**Comment by Destarianon** [comment]
Can we clarify what is meant by "query by name"?
I am performing queries by hostname, rather than IP address but I am still failing to query servers. I don't see documentation for any other kind of "name" that can be provided.

Additional debug output:
```
Q#1 Requesting external access token ...
Q#1 Requesting deviceId access token ...
Q#1 POST: https://api.epicgames.dev/auth/v1/accounts/deviceid
Q#1 https://api.epicgames.dev/auth/v1/accounts/deviceid HTTP-->
Q#1 https://api.epicgames.dev/auth/v1/accounts/deviceid <--HTTP 200
Q#1 POST: https://api.epicgames.dev/auth/v1/oauth/token
Q#1 https://api.epicgames.dev/auth/v1/oauth/token HTTP-->
Q#1 https://api.epicgames.dev/auth/v1/oauth/token <--HTTP 200
Q#1 POST: https://api.epicgames.dev/matchmaking/v1/0a18471f93d448e2a1f60e47e03d3413/filter
Q#1 https://api.epicgames.dev/matchmaking/v1/0a18471f93d448e2a1f60e47e03d3413/filter HTTP-->
Q#1 https://api.epicgames.dev/matchmaking/v1/0a18471f93d448e2a1f60e47e03d3413/filter <--HTTP 200
Q#1 Query failed with error Error: Server not found
    at palworld.queryInfo (file:///usr/lib/node_modules/gamedig/protocols/epic.js:126:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async palworld.run (file:///usr/lib/node_modules/gamedig/protocols/epic.js:34:5)
    at async palworld.run (file:///usr/lib/node_modules/gamedig/protocols/palworld.js:15:5)
    at async palworld.runOnce (file:///usr/lib/node_modules/gamedig/protocols/core.js:80:5)
    at async palworld.runOnceSafe (file:///usr/lib/node_modules/gamedig/protocols/core.js:54:22)
    at async QueryRunner._attempt (file:///usr/lib/node_modules/gamedig/lib/QueryRunner.js:118:12)
    at async QueryRunner.run (file:///usr/lib/node_modules/gamedig/lib/QueryRunner.js:95:26)
    at async GameDig.query (file:///usr/lib/node_modules/gamedig/lib/gamedig.js:11:12)
Error: Failed all 2 attempts
    at QueryRunner.run (file:///usr/lib/node_modules/gamedig/lib/QueryRunner.js:106:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GameDig.query (file:///usr/lib/node_modules/gamedig/lib/gamedig.js:11:12)
Attempt #1 - Port=8211 Retry=0:
Error: Server not found
    at palworld.queryInfo (file:///usr/lib/node_modules/gamedig/protocols/epic.js:126:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async palworld.run (file:///usr/lib/node_modules/gamedig/protocols/epic.js:34:5)
    at async palworld.run (file:///usr/lib/node_modules/gamedig/protocols/palworld.js:15:5)
    at async palworld.runOnce (file:///usr/lib/node_modules/gamedig/protocols/core.js:80:5)
    at async palworld.runOnceSafe (file:///usr/lib/node_modules/gamedig/protocols/core.js:54:22)
    at async QueryRunner._attempt (file:///usr/lib/node_modules/gamedig/lib/QueryRunner.js:118:12)
    at async QueryRunner.run (file:///usr/lib/node_modules/gamedig/lib/QueryRunner.js:95:26)
    at async GameDig.query (file:///usr/lib/node_modules/gamedig/lib/gamedig.js:11:12)
```

**Comment by CosminPerRam** [comment]
> I've been able to successfully query my server by name instead of IP address just by adjusting the filter.

Could you provide some more explainations or a code snippet regarding this?

**Comment by jammsen** [comment]
Yeah @dkoz do you mean by "dns-name" or what do you mean? Please clarify.

**Comment by xstar97** [comment]
I've developed a simple RCON API service in Go for Palworld, which you can find at [palworld-query-api](https://github.com/xstar97/palworld-query-api). The repository includes a container image for easy deployment.

This API heavily relies on the `rcon-cli` tool from another repository, available [here](https://github.com/gorcon/rcon-cli). While the Docker image automatically downloads this tool for you, if you're running the Go code or binary directly, you'll need to obtain it yourself.

Feel free to check it out and contribute if you're interested!

plz delete if not allowed :)

**Comment by jammsen** [comment]
> I've developed a simple RCON API service in Go for Palworld, which you can find at [palworld-query-api](https://github.com/xstar97/palworld-query-api). The repository includes a container image for easy deployment.
> 
> This API heavily relies on the `rcon-cli` tool from another repository, available [here](https://github.com/gorcon/rcon-cli). While the Docker image automatically downloads this tool for you, if you're running the Go code or binary directly, you'll need to obtain it yourself.
> 
> Feel free to check it out and contribute if you're interested!
> 
> plz delete if not allowed :)

Please dont use that binary or the image itself like it is, the Maintainer knows since weeks about CVEs and isnt patching them, please use my fix for that:

https://github.com/jammsen/docker-palworld-dedicated-server/blob/develop/Dockerfile#L5
Line 5-17

**Comment by CosminPerRam** [comment]
@jonnerz over on the Discord server noted that Palworld moved to what seems a proprietary master server service, api endpoint [here](https://api.palworldgame.com/server/list).

**Comment by Maxence1502** [comment]
Is there a way to filter using this API ?
It’s very long to fetch all pages

**Comment by Destarianon** [comment]
That also appears like it wouldn't work if the server is configured as not publicly listed.

**Comment by jammsen** [comment]
Makes sense, in the old api even people who disbaled community-mode, were listed in that server-list.
I guess they are trying to start fresh, which makes also sense, because the communit-mode setting totally change in name -> publiclobby.

**Comment by xstar97** [comment]
> @Jonnerz over on the Discord server noted that Palworld moved to what seems a proprietary master server service, api endpoint [here](https://api.palworldgame.com/server/list).

thanks, implemented in my query api service now :)

**Comment by Maxence1502** [comment]
How do you find your server within this list with so many pages ?

**Comment by CosminPerRam** [comment]
![image](https://github.com/gamedig/node-gamedig/assets/7972857/ebf5eed9-38d1-43b0-8bc4-bf8ceb2b2764)

Here is a snippet of the first implementation that I'm working on now, and that's not even a complete query.

Unfortunately there doesnt seem to be any way to filter by ip or port, there is a search functionality but doesnt look in the address/port fields.

What we can do for now is to just query a page, check if our server is in it, and if not just query the next page, until we find our server and return. This is O(n) and it's bad for performance (on both sides) and it comes down to luck I guess for how up your server is in the list.

There could be much more of this API but we don't have any docs at all on it.

**Comment by CosminPerRam** [comment]
We could add an option to encourage players to also include a field like "name" for palworld to try to narrow down the list, but it doesnt sound very great.

**Comment by xstar97** [comment]
> How do you find your server within this list with so many pages ?

we are getting off topic here, but the jist is...i cached the entire 150+ pages and query and filter that instead.

**Comment by Maxence1502** [comment]
The latest update of Palworld added an API to query players, can we use that ?
https://tech.palworldgame.com/api/rest-api/players

**Comment by jammsen** [comment]
That RESTAPI needs Basci-Auth with "admin:ADMIN_PASSWORD" so you might just need to extend things here in a way. But i forwarded @CosminPerRam some stuff im working on with my Palworld Docker Image.

**Comment by CosminPerRam** [comment]
Yes, this looks really good!

**Comment by CosminPerRam** [comment]
Successfully made a query on a server provided by @jammsen, if anyone encounters issues please mention or make a new issue (:

**Comment by jammsen** [comment]
Testing from my side, positive and negative worked like a charm too.
