### ISSUE TITLE
feat: Support Minecraft favicon

### ISSUE THREAD

**Issue by ryush00** [gamedig/node-gamedig#566]
**What is this feature about?**
Currently gamedig is deleting Minecraft favicon data. I couldn't find its context but maybe performance problem?

It will be better if we can set option to leave favicon data.

**Additional context/references**
https://github.com/gamedig/node-gamedig/blob/2b58e0d233e5c66fb92afddda1cc7d3f2a490ceb/protocols/minecraftvanilla.js#L48

**Comment by CosminPerRam** [comment]
Hey, this line was added in [this](https://github.com/gamedig/node-gamedig/commit/c82554ad1a6ab5b694bbce4da54bc92c10ff729a) commit, which was made roughly 10 years ago and I couldn't find whatsoever the reason for doing this (other than preventing clutter in the output object maybe?) or potential problems of this field, will make a PR soon.
