### ISSUE TITLE
Support Soulmask game

### ISSUE THREAD

**Issue by Maxence1502** [gamedig/node-gamedig#570]
Hello,

Is it possible to support this game : https://store.steampowered.com/app/2646460/Soulmask/

Thank you :)

**Comment by xCausxn** [comment]
Hey do you have a server up currently? Do you have a link to the documentation for setting one up?

Helps devs not have to go hunting for information :)

**Comment by Maxence1502** [comment]
Yes, you can test on this server : 45.90.161.4:15651 (query port 15652)

There is no documentation to setup currently :(

**Comment by SergejKembel** [comment]
Here is a documentation: https://soulmask.fandom.com/wiki/Private_Server but there are docker images, that you can use for fast testing.

Works with simple valve protocol - wanted to commit it myself, but tools/generate_games_list.js destroyed my commit :D

**Comment by CosminPerRam** [comment]
Added via #572
