### ISSUE TITLE
bug: possible misspelling and duplicate of theforest

### ISSUE THREAD

**Issue by dgibbs64** [gamedig/node-gamedig#577]
**Describe the bug**
Possible duplicate and misspelling of a game. I have found an id called `theforest` and another called `theforrest`. I believe `theforrest` is a misspelling of the game https://store.steampowered.com/app/242760/The_Forest/

**Comment by xCausxn** [comment]
So this looks like a backwards compatibility entry, as previously it was called forrest.

https://github.com/gamedig/node-gamedig/blob/fccd61c4eaac9a80a1f07021f04435fbc182832d/lib/games.js#L923

@CosminPerRam we could probably just remove that entry and set the `extra.old_id` to forrest instead.
