### ISSUE TITLE
bug: Not working for Assetto Corsa

### ISSUE THREAD

**Issue by codewhizz** [gamedig/node-gamedig#583]
**Describe the bug**
Whenever I execute the code, I get Server is offline, error: Error: Failed all 2 attempts

**Steps To Reproduce**
Please check the attached images

**Expected behavior**
It should show the details of assettocorsa server. Servers are online. But it fails everytime

**Screenshots or Data**
Uploaded

**Additional context**
Please check the attached images

![image](https://github.com/gamedig/node-gamedig/assets/74320321/0c98bd45-4f02-48e5-9a2e-dbd78932ff7c)

![image](https://github.com/gamedig/node-gamedig/assets/74320321/1941623d-f803-48bd-abae-ca7c675746f6)

**Comment by xCausxn** [comment]
Hey is that port the HTTP port in the server config?
