### ISSUE TITLE
tracking: Bun UdpSocket.unref

### ISSUE THREAD

**Issue by Douile** [gamedig/node-gamedig#589]
https://github.com/oven-sh/bun/issues/12561

When unref is supported in Bun we should support it as a runtime (we might want to do some more tests).

**Comment by xCausxn** [comment]
The linked PR looks to have been merged and closed, so we can likely expect a release shortly.

**Comment by xCausxn** [comment]
https://github.com/oven-sh/bun/releases/tag/bun-v1.1.21
https://bun.sh/blog/bun-v1.1.21#fixed-unref-in-node-dgram-before-socket-is-connected

Looks like the release went live now.
