### ISSUE TITLE
bug: typo in arma reforgers GameDig Type ID	

### ISSUE THREAD

**Issue by Misfit-Ha** [gamedig/node-gamedig#609]
**Describe the bug**
in [game list page](https://github.com/gamedig/node-gamedig/blob/master/GAMES_LIST.md) reforger's id is written "armareforger" it should instead say "armare"

**Steps To Reproduce**
$ npx gamedig --type armareforger --host <ip> --port 2001
{"error":"Invalid game: armareforger"}

$ npx gamedig --type armare --host <ip> --port 2001
works

**Comment by CosminPerRam** [comment]
Hmmm, it works just fine to me:
![image](https://github.com/user-attachments/assets/c0b26f15-b5f0-4abc-9ce5-56a6b2ccce2c)

And the game has the proper id defined:
![image](https://github.com/user-attachments/assets/81f3f70c-f4d0-4b05-a101-0272033b4e65)

This seems to be a problem related to npx, I haven't really used it much but it seems that this runs gamedig v4 (as in v5 we have changed the ids), [may this be related](https://github.com/npm/cli/issues/2329)?

**Comment by CosminPerRam** [comment]
@Misfit-Ha hey, have you found something out?
