### ISSUE TITLE
bug: player list of official server ark survival ascended always empty

### ISSUE THREAD

**Issue by Overfly3** [gamedig/node-gamedig#615]
player list of official server ark survival ascended always empty

**Comment by xCausxn** [comment]
Hey @Overfly3 

As per the game notes: https://github.com/gamedig/node-gamedig/blob/master/GAMES_LIST.md#epic-online-services-eos-protocol

ARK Survival Ascended uses the EOS protocol which does not provide players data.

This is unfortunately a limitation of the protocol at Epic.

**Comment by CosminPerRam** [comment]
Closed as per @xCausxn's comment.
Feel free to reopen/comment for additional questions.
