### ISSUE TITLE
bug: Deus Ex should be gamespy-1

### ISSUE THREAD

**Issue by dgibbs64** [gamedig/node-gamedig#618]
**Describe the bug**
I noticed that Deus Ex servers respond to gamespy 1 but not gamespy 2 as the list states 

**Steps To Reproduce**
here is an example server to query against
207.180.246.62:7790 game
207.180.246.62:7791 query

**Expected behavior**
Deus Ex to return a query

**Comment by CosminPerRam** [comment]
The game has been added as suported more than 10 years ago [in this mega commit](https://github.com/gamedig/node-gamedig/commit/bc6b5c92256b7805dda420dcc9b6f10555a6d91a#diff-16ea8a46f7ae6f4cafc8dbf4fa9d707e26b3e6b87f0ea3775cf5491003918df4R76).
After a not so extensive search I couldn't find anything related to gamespy 1 or 2 being the protocol nor any servers that would respond to any.

**Comment by dgibbs64** [comment]
Yeah that's the issue I'm finding sometimes as well. Cant find any history on why the protocol was chosen. But as I am testing more older servers I am picking up a few issues.

**Comment by CosminPerRam** [comment]
After firing up a GOTY Dedicated server of it, upon querying with GameSpy1, it does not respond back, but I do get this in the console: `ScriptLog: UdpServerQuery: Unknown query: status`. 
I'm not sure if the original game behaves differently than the GOTY one.
GameSpy2 does not responds/logs to the console at all.

I'd like to find a bunch of other servers to test this upon before changing it.

**Comment by CosminPerRam** [comment]
Nevermind! I was querying the wrong ports (I kept trying `7792`), I think this can be safely changed as this is a fresh server.

**Comment by dgibbs64** [comment]
The reason im picking this stuff up is because I am looking though the https://333networks.com/ and other master servers and finding servers to test against. I am looking at this project and its helping me find them. https://github.com/cetteup/GameserverLister

**Comment by mmorrisontx** [comment]
The mega commit was from me scouring through the various old query scripts and throwing together all of the protocol info I could find. Not all of it was verified (it was hard to find servers for some of these games to test with, even back then), so I would not be surprised at all if some of the more niche server types have incorrect info.
