### ISSUE TITLE
bug: Solider of fortune reponses to both Quake 2 and Gamespy but not Quake 1

### ISSUE THREAD

**Issue by dgibbs64** [gamedig/node-gamedig#619]
**Describe the bug**
Solider of Fortune "sof" does not respond to quake1 protocol but does respond to both quake2 and gamespy1 queries. Also it is worth noting that the gamespy query seems to return more useful data. 

**Steps To Reproduce**
Example server 
Game: 5.135.46.179:28912
Query: 5.135.46.179:28913

https://ismygameserver.online/quake2/5.135.46.179:28912
https://ismygameserver.online/gamespy/5.135.46.179:28912
https://ismygameserver.online/sof/5.135.46.179:28912

Side note. I have noticed that Unreal 2004, Red Orchestra and Killing Floor also responds to 2 query types (see the drop-down on https://ismygameserver.online

**Comment by CosminPerRam** [comment]
The main scope of this PR has been done in #623.
The side note has been transformed into an issue that was similar for another game in #608.
