### ISSUE TITLE
fetching day time from 7 days to die server

### ISSUE THREAD

**Issue by aman7** [gamedig/node-gamedig#647]
**What is this feature about?**
it should allow us to fetch current day, time of the server. so we can determine when is next horde night, in game days and also in real life.

**Comment by xCausxn** [comment]
Looking at the raw response from the query, this information does not seem to exposed via the steam a2s query.

**Comment by CosminPerRam** [comment]
If you add `requestRules: true` to the options (or `--requestRules true` for the CLI), the query will attempt to get more informations via the rules query (which you can access afterwards by `state.raw.rules`). 

Doing this on a random server I see that there are a few fields related to time:
```
BedrollExpiryTime: '14',
CurrentServerTime: '3839767',
LandClaimExpiryTime: '14'
```
And some related to day: 
```
DayCount: '3',
DayLightLength: '18',
DayNightLength: '60',
LootRespawnDays: '3',
```
You can access them by doing for example `state.raw.rules['DayCount']`.

Note that these fields might not appear on all servers and by using this option the query time will increase.
Closing this as the game doesn't use a proprietary protocol and/or these fields are not standardized.

Hope you can access the data that you need through what I mentioned, feel free to comment/reopen for more questions if something isn't clear.
