### ISSUE TITLE
bug: Minecraft server name's are duplicated

### ISSUE THREAD

**Issue by mason-rogers** [gamedig/node-gamedig#655]
**Describe the bug**
The `name` for minecraft servers is duplicated

**Steps To Reproduce**
Query a minecraft server (vanilla in my instance)

**Expected behavior**
Name to be "god coolest minecraft server", as it in in `raw.vanilla.raw.description.text`

**Screenshots or Data**
![image](https://github.com/user-attachments/assets/71634af0-8987-4b8d-bbbe-66a47aed4b11)

**Additional context**
Gamedig version: Latest (5.1.4 at time of issue)

**Comment by CosminPerRam** [comment]
There's a few possibilities of why this could happen, but we'll need more information to debug this.

If it's a publicly available server, can you provide the ip and port? If not, can you do the query with `debug: true` and put the logs here? (make sure to remove the ip)

**Comment by mason-rogers** [comment]
You can have the IP. 95.216.251.232:25566

I've also tested another minecraft server on a different ip and it seemed to do the same

**Comment by ZixeSea** [comment]
As of recent it also seems like online players is missing from the data, tested multiple servers.

If you run a `console.log` on the const `str` in minecraftvanilla.js at line 44 you won't see any player info outside `players.max` and `players.online` (where players.online is always 0).

_**Both `name` and `numplayers` for bedrock are included, this only seems to be a minecraft vanilla problem.**_

**Comment by CosminPerRam** [comment]
Hey @mason-rogers, could you test the branch?
I have tested on the server you provided and all is good.

**Comment by CosminPerRam** [comment]
> Seems like a problem with BungeeCord

@ZixeSea could you provide additional context about this?

**Comment by ZixeSea** [comment]
@CosminPerRam I have done some more research and it doesn't seem to be BungeeCord, it's probably an user problem (like some config/setting they have setup).

I run a API that uses GameDig to collect info and don't really use it myself so it's not always easy to find out what people are doing.

**Comment by CosminPerRam** [comment]
I've merged the fix as I've had no response from OP of it for some time now, if there still are problems please mention.
